*
* BCPLMAIN-WIP.ASM
*
* Working reconstruction proposal for the native IBM System/370 BCPL
* runtime entry expected by the surviving Cambridge CG370.
*
* STATUS
* ------
* This is deliberately a WIP, not a claim to be the historical BCPLMAIN.
* Code is present where the project has direct evidence or a narrow,
* testable inference.  Missing runtime facilities are called out below.
*
* PRIMARY CURRENT MILESTONE
* -------------------------
* Supply enough of the native runtime contract to execute the Richards
* factorial test generated by the Cambridge compiler, while preserving
* the shape needed for a fuller reconstruction.
*
* EVIDENCE: COMPILED-MODULE ENTRY
* -------------------------------
* Generated modules begin:
*
*          STM 14,12,12(13)
*          L   4,12(15)
*          BCR 15,4
*          DC  AL2(L998-L999)
*          DC  A(BCPLMAIN)
*
* Job 940 established experimentally that BCPLMAIN receives control with
* R15 still equal to the generated module base.
*
* The halfword at module+10 is the byte length from L999 to L998.
*
* EVIDENCE: GLOBAL TRAILER
* ------------------------
* CGGLOBAL emits, immediately before L998:
*
*          DC F'4*MAXGN'
*          DC F'0'
*          repeated:
*              DC F'4*GLOBAL-NUMBER'
*              DC A(GLOBAL-ADDRESS)
*
* Job 941 established that the factorial module can be decoded through
* this structure and that its final pair is G!1 = START.
*
* The generic backward scan below is a reconstruction proposal.  It
* relies on the zero address word preceding the exported-global pairs.
* It has not yet been validated with a module exporting several globals.
*
* EVIDENCE: GENERATED REGISTER CONTRACT
* -------------------------------------
* From CGHDR:
*
*   R1   R.K4   expected constant 4096
*   R2   R.K8   expected constant 8192
*   R3   R.K12  expected constant 12288
*   R4   R.B    branch/callee address
*   R5   R.P    current BCPL workspace pointer
*   R6   R.L    BCPL linkage register
*   R7   R.A1   argument 1 / function result
*   R8   R.A2   argument 2
*   R9   R.A3   argument 3
*   R10  R.A4   argument 4
*   R11  R.S    system-vector base
*   R12  R.G    global-vector base
*   R14  R.A    compiler scratch/linkage register
*   R15  R.W    new-workspace pointer
*
* Generated text also says:
*
*          USING 4096,1,2,3
*
* so a general runtime must establish R1/R2/R3, even though the first
* factorial module does not use them.
*
* NEW EVIDENCE FROM JOB 943: R0 MUST BE ZERO
* ------------------------------------------
* The factorial function tests its base case using:
*
*          CR 7,0
*
* Our first native-runtime probe left R0 holding the WRITEF address.
* Recursion therefore passed through N=0.  At the S0C4, R7 was -61,
* R15 had reached the end of the temporary workspace, and the failing
* instruction was the recursive-entry STM at module offset X'4C'.
*
* The startup below therefore establishes R0=0 immediately before
* entering BCPL code.  Runtime primitives must preserve that invariant.
*
* EVIDENCE: GLOBAL VECTOR
* -----------------------
* Generated WRITEF call:
*
*          L    4,304(12)
*          BALR 6,4
*
* proves R12 is G and global N is at byte displacement 4*N.
*
* BLIB expects G!0 to describe the allocated global-vector extent and
* recognizes an uninitialized global sentinel:
*
*          X'C7D3F000' + 4*N
*
* This WIP allocates globals 0..150 statically and initializes that
* sentinel convention.  Dynamic sizing/GETMAIN remains to be recovered.
*
* EVIDENCE: SYSTEM VECTOR
* -----------------------
* CGHDR defines:
*
*          S.COUNT       = 20
*          S.FIN         = 40
*          S.STKCK       = 60
*          S.STKCKCOUNT  = 80
*
* Generated procedure return is:
*
*          BCR 15,11
*
* Generated FINISH is:
*
*          BC  15,40(11)
*
* The vector below therefore has executable branch entries at those
* offsets.  The exact historical bodies are not yet available.
*
* PROCEDURE RETURN INFERENCE
* --------------------------
* Generated entry saves R4..R6 (or more) at 0(R15), then sets R5=R15.
* Calls place the return address in R6.  The proposed return trampoline:
*
*          LM   4,6,0(5)
*          BCR  15,6
*
* restores callee address, previous P, and linkage, then returns.
* This is strongly implied by CGSAVE/CGAPPLY but is not yet independently
* validated by a successful native run.
*
* MACHINE-DEPENDENT GLOBALS KNOWN TO BELONG TO BCPLMAIN
* -----------------------------------------------------
* BLIB explicitly states GETBYTE and PUTBYTE are machine-code routines
* forming part of BCPLMAIN.  Their contracts are known:
*
*   GETBYTE(S,I)       -> byte at offset I from BCPL vector S
*   PUTBYTE(S,I,BYTE)  -> store low 8 bits at byte offset I
*
* BCPL pointers are word pointers; generated string code shifts target
* byte addresses right by two before passing them as BCPL values.
* Implementations below therefore convert S back to a byte address by
* shifting left two.
*
* FACTORIAL-ONLY ACCOMMODATION
* ----------------------------
* WRITEF is a BLIB/library routine, not proven to be part of BCPLMAIN.
* Until BLIB is linked natively, G!76 is installed as a no-op stub so
* the factorial control-flow test can execute.  This must not survive as
* the final WRITEF implementation.
*
* MVS ENTRY/EXIT
* --------------
* The generated module prefix has already executed the standard:
*
*          STM 14,12,12(13)
*
* before entering BCPLMAIN.  This WIP leaves R13 unchanged and uses that
* caller save area for final return with LM 14,12,12(13).
*
* IMPORTANT UNKNOWN: CGHDR reserves FWSP=96 relative to R13 for FIX/FLOAT
* workspace.  A standard 72-byte caller save area does not establish that
* historical contract.  Floating-point generated code is therefore NOT
* supported by this WIP.  A real BCPLMAIN probably establishes its own
* larger R13 work/save area and chains it according to MVS convention.
*
* OTHER RUNTIME FACILITIES KNOWN TO EXIST BUT NOT YET RECONSTRUCTED
* -----------------------------------------------------------------
* SYS3 LIBHDR identifies the following runtime surface.  Their existence
* is known; this file does not pretend their full interfaces are known
* merely from the global names.
*
*   G2  SETPM
*   G3  ABORT              BLIB supplies high-level reporting; low-level
*                          program-interrupt capture is still unknown.
*   G4  BACKTRACE
*   G5  ERRORMESSAGE
*   G6  SAVEAREA           this WIP publishes R13>>2 provisionally.
*   G7  UNLOADALL
*   G8  LOADFORT
*   G9  UNLOAD
*   G10 LOAD               segment/module loader contract still required.
*
*   G11..G26               stream selection and record I/O, including
*                          RDCH, WRCH, READREC, WRITEREC, SKIPREC.
*
*   G27..G39               time/date, STOP, long jump, logging, terminal
*                          and parameter services.
*
*   G40 APTOVEC            allocation primitive.
*   G41..G51               dataset/library/member discovery and close.
*
*   G52 LOADPOINT          published provisionally for main module.
*   G53 ENDPOINT            published provisionally for main module.
*   G54 STACKBASE          published by this WIP.
*   G55 STACKEND           published by this WIP.
*   G56 STACKHWM           BLIB implementation exists; not installed here.
*   G57 OS/CMS marker      known to exist; exact value convention pending.
*
*   G58..G84               library helpers, postmortem, FORTRAN bridge,
*                          break/error support.
*
*   G85 GETBYTE            implemented here.
*   G86 PUTBYTE            implemented here.
*   G87..G99               vector allocation, arithmetic, block-file and
*                          MOVEBYTES services.
*
* LOAD/UNLOAD deserves its own reconstruction from historical loader data.
* BLIB shows SAVEAREA!29 as the head of a load list and tests bit X'80000000'
* in load-list word 9 for BCPL modules.  That is evidence, not yet enough
* to implement the loader contract safely.
*
* ----------------------------------------------------------------------
*
BCPLMAIN CSECT
*
* Preserve the compiled-module base before R3 is repurposed as R.K12.
*
         LR    3,15
         BALR  10,0
         USING *,10
         ST    3,MODBASE
*
* Locate L998 = module base + unsigned positive halfword at module+10.
* CG370 limits a generated section to less than 16K bytes, so LH is safe.
*
         LH    0,10(3)
         LR    2,3
         AR    2,0
         ST    2,MODEND
*
* Initialize a static global vector with the historical unset sentinel.
*
         LA    12,GLOBV
         LA    1,GLOBCNT
         ST    1,0(12)
         LA    2,4(12)
         L     3,=X'C7D3F004'
GINIT    ST    3,0(2)
         A     3,=F'4'
         LA    2,4(2)
         BCT   1,GINIT
*
* Find the trailer sentinel by scanning backward in two-word units.
* A pair whose second word is zero is treated as [4*MAXGN,0].
*
         L     8,MODEND
GSCAN    AH    8,=H'-8'
         L     9,4(8)
         LTR   9,9
         BC    7,GSCAN
*
* Reject modules requiring more globals than this static WIP provides.
*
         L     0,0(8)
         C     0,=F'600'
         BC    2,GTOOBIG
         ST    8,TRAILER
*
* Re-scan from the module end and install each exported global.
*
         L     8,MODEND
GINST    AH    8,=H'-8'
         L     9,4(8)
         LTR   9,9
         BC    8,GIDONE
         L     1,0(8)
         C     1,=F'600'
         BC    2,GTOOBIG
         LR    2,12
         AR    2,1
         ST    9,0(2)
         BC    15,GINST
*
* G!1 must now contain START rather than the unset sentinel.
*
GIDONE   L     4,4(12)
         C     4,=X'C7D3F004'
         BC    8,NOSTART
*
* Publish the subset of runtime globals whose representation is supported
* strongly enough for this WIP.
*
* G!6 = provisional BCPL word pointer for the current MVS save area.
*
         LR    1,13
         SRL   1,2
         ST    1,24(12)
*
* G!52/G!53 = provisional main-program word-address extent.
*
         L     1,MODBASE
         SRL   1,2
         ST    1,208(12)
         L     1,MODEND
         SRL   1,2
         ST    1,212(12)
*
* G!54/G!55 = BCPL word pointers delimiting static WIP stack/workspace.
*
         LA    1,WORK
         SRL   1,2
         ST    1,216(12)
         L     1,=A(WORKEND)
         SRL   1,2
         ST    1,220(12)
*
* G!76 = temporary no-op WRITEF for the factorial milestone.
* G!85/G!86 = machine-dependent byte primitives required by BLIB.
*
         LA    1,WRITEST
         ST    1,304(12)
         LA    1,GETBYTE
         ST    1,340(12)
         LA    1,PUTBYTE
         ST    1,344(12)
*
* Establish S, initial P/W, and the absolute-base constants required by
* generated USING 4096,1,2,3 code.
*
         LA    11,SYSV
         LA    15,WORK
         LR    5,15
         L     1,=F'4096'
         L     2,=F'8192'
         L     3,=F'12288'
*
* START receives no arguments.  Clear argument registers and linkage.
* R10 has served as our assembler base and must cease being one now.
*
         SR    6,6
         SR    7,7
         SR    8,8
         SR    9,9
         SR    10,10
*
* Job 943 makes this initialization a required runtime invariant.
*
         SR    0,0
         BCR   15,4
*
* START is expected to terminate through S.FIN.  Returning here is treated
* as a WIP runtime failure.
*
BADRETN  LM    14,12,12(13)
         LA    15,36
         BR    14
*
* Bootstrap failures before START.
*
GTOOBIG  LM    14,12,12(13)
         LA    15,16
         BR    14
NOSTART  LM    14,12,12(13)
         LA    15,20
         BR    14
*
* Put literals used by startup inside the startup base-register region.
*
         LTORG
*
* From here on R10 is not a runtime base.  Executable system-vector
* services use R11, whose value is SYSV in generated BCPL code.
*
         DROP  10
*
***********************************************************************
* SYSTEM VECTOR
*
* Each public offset is a four-byte branch followed by padding to the
* next 20-byte slot.  This layout is a reconstruction proposal matching
* the offsets in CGHDR; the historical instruction sequence is unknown.
***********************************************************************
SYSV     EQU   *
         USING SYSV,11
         BC    15,RETIMPL
         DS    8H
*
* S.COUNT = 20
*
SYSCOUNT BC    15,CNTIMPL
         DS    8H
*
* S.FIN = 40
*
SYSFIN   BC    15,FINIMPL
         DS    8H
*
* S.STKCK = 60
*
SYSSTK   BC    15,STKIMPL
         DS    8H
*
* S.STKCKCOUNT = 80
*
SYSSTKC  BC    15,STKCIMP
*
***********************************************************************
* PROCEDURE RETURN
*
* Strong inference from CGSAVE/CGAPPLY, awaiting successful native proof.
***********************************************************************
RETIMPL  LM    4,6,0(5)
         BCR   15,6
*
***********************************************************************
* CALL-COUNT SERVICE -- STUB
*
* CG370 emits BAL R14,S.COUNT(R11) followed by an inline fullword.
* A minimally non-destructive stub must skip that word on return.
* Actual counter semantics remain to be reconstructed.
***********************************************************************
CNTIMPL  LA    14,4(14)
         BR    14
*
***********************************************************************
* FINISH
*
* Restore the MVS registers saved by the generated module prefix.
* This is sufficient for the current factorial milestone.  STOP/ABORT and
* propagation of a BCPL result code remain separate reconstruction work.
***********************************************************************
FINIMPL  LM    14,12,12(13)
         SR    15,15
         BR    14
*
***********************************************************************
* STACK CHECK -- STUB
*
* This currently performs no check.  Historical overflow rules, marker
* initialization, and ABORT integration must be reconstructed.
***********************************************************************
STKIMPL  BR    14
*
***********************************************************************
* STACK CHECK + CALL COUNT -- STUB
*
* CG370 places an inline fullword after this BAL form, so skip it.
***********************************************************************
STKCIMP  LA    14,4(14)
         BR    14
*
***********************************************************************
* TEMPORARY WRITEF
*
* Factorial-only accommodation.  Arguments arrive in R7 onward under the
* normal BCPL calling convention.  Do not modify R0 or R1-R3.
***********************************************************************
WRITEST  BCR   15,6
*
***********************************************************************
* GETBYTE(S,I) -> R7
*
* S is a BCPL word pointer.  I is an unrestricted byte offset.
***********************************************************************
GETBYTE  LR    14,7
         SLL   14,2
         AR    14,8
         SR    7,7
         IC    7,0(14)
         BCR   15,6
*
***********************************************************************
* PUTBYTE(S,I,BYTE)
*
* S in R7, I in R8, BYTE in R9.  Store the low eight bits.
***********************************************************************
PUTBYTE  LR    14,7
         SLL   14,2
         AR    14,8
         STC   9,0(14)
         BCR   15,6
*
***********************************************************************
* WIP DATA
***********************************************************************
         DS    0F
MODBASE  DC    F'0'
MODEND   DC    F'0'
TRAILER  DC    F'0'
*
* Static global-vector capacity.  FIRSTFREEGLOBAL in SYS3 LIBHDR is 150.
* Whether the historical BCPLMAIN sized G to exactly this value or used a
* larger installation-dependent vector remains unknown.
*
GLOBCNT  EQU   150
GLOBV    DC    F'150'
         DS    150F
*
* Static development workspace.  This is not the historical allocation
* policy.  Replace with recovered MVS storage management and stack marker
* initialization when that contract is understood.
*
WORK     DS    4096F
WORKEND  EQU   *
*
         END   BCPLMAIN
