*
* BCPLMAIN-WIP.ASM
*
* Working reconstruction proposal for the native IBM System/370 BCPL
* runtime entry expected by the surviving Cambridge CG370.
*
* STATUS
* ------
* This is deliberately a WIP, not a claim to be historical BCPLMAIN.
* Code is present where the project has direct evidence or a narrow,
* testable inference.  Missing runtime facilities are called out below.
*
* PRIMARY CURRENT MILESTONE
* -------------------------
* Supply enough of the native runtime contract to execute the Richards
* factorial test generated by the Cambridge compiler, while preserving
* the shape needed for a fuller reconstruction.
*
* EVIDENCE: COMPILED-MODULE ENTRY
* -------------------------------
* Generated modules begin:
*
*          STM 14,12,12(13)
*          L   4,12(15)
*          BCR 15,4
*          DC  AL2(L998-L999)
*          DC  A(BCPLMAIN)
*
* Job 940 established that BCPLMAIN receives control with
* R15 still equal to the generated module base.
*
* The halfword at module+10 is the byte length from L999 to L998.
*
* EVIDENCE: GLOBAL TRAILER
* ------------------------
* CGGLOBAL emits, immediately before L998:
*
*          DC F'4*MAXGN'
*          DC F'0'
*          repeated:
*              DC F'4*GLOBAL-NUMBER'
*              DC A(GLOBAL-ADDRESS)
*
* Job 941 established that the factorial module can be decoded through
* this structure and that its final pair is G!1 = START.
*
* The generic backward scan below is a reconstruction proposal.  It
* relies on the zero address word preceding the exported-global pairs.
* It is not yet validated with a module exporting several globals.
*
* EVIDENCE: GENERATED REGISTER CONTRACT
* -------------------------------------
* From CGHDR:
*
*   R1   R.K4   expected constant 4096
*   R2   R.K8   expected constant 8192
*   R3   R.K12  expected constant 12288
*   R4   R.B    branch/callee address
*   R5   R.P    current BCPL workspace pointer
*   R6   R.L    BCPL linkage register
*   R7   R.A1   argument 1 / function result
*   R8   R.A2   argument 2
*   R9   R.A3   argument 3
*   R10  R.A4   argument 4
*   R11  R.S    system-vector base
*   R12  R.G    global-vector base
*   R14  R.A    compiler scratch/linkage register
*   R15  R.W    new-workspace pointer
*
* LIVE ARGUMENT-LINKAGE EVIDENCE
* ------------------------------
* Native regression Tests 11-14 now confirm the generated call-time
* argument convention, not merely the symbolic register names in CGHDR.
*
* Job 986 (Test 11) proved argument 1 is passed in R7.
* Job 990 (Test 13) proved:
*
*          argument 1 -> R7
*          argument 2 -> R8
*
* Job 992 (Test 14) proved:
*
*          argument 1 -> R7
*          argument 2 -> R8
*          argument 3 -> R9
*
* In Test 14 the caller loaded V, I, X into R7, R8, R9 immediately
* before BALR.  The generated three-argument callee began:
*
*          STM 4,9,0(15)
*          LR  5,15
*
* and then used R7/R8 to form V!I while storing R9 through the
* computed address.  This is direct executable evidence for native
* machine-code runtime entries such as PUTBYTE(S,I,BYTE): their first
* three BCPL arguments arrive in R7, R8, and R9 respectively.
*
* Generated text also says:
*
*          USING 4096,1,2,3
*
* so a general runtime must establish R1/R2/R3, even though the first
* factorial module does not use them.
*
* NEW EVIDENCE FROM JOB 943: R0 MUST BE ZERO
* ------------------------------------------
* The factorial function tests its base case using:
*
*          CR 7,0
*
* Our first native-runtime probe left R0 holding the WRITEF address.
* Recursion therefore passed through N=0.  At the S0C4, R7 was -61,
* R15 had reached the end of the temporary workspace, and the failing
* instruction was the recursive-entry STM at module offset X'4C'.
*
* The startup below therefore establishes R0=0 immediately before
* entering BCPL code.  Runtime primitives must preserve that invariant.
*
* EVIDENCE: GLOBAL VECTOR
* -----------------------
* Generated WRITEF call:
*
*          L    4,304(12)
*          BALR 6,4
*
* proves R12 is G and global N is at byte displacement 4*N.
*
* BLIB expects G!0 to describe the allocated global-vector extent and
* recognizes an uninitialized global sentinel:
*
*          X'C7D3F000' + 4*N
*
* This WIP allocates a modest static global-vector extent.
* It initializes the historical sentinel convention.
* Dynamic sizing/GETMAIN remains to be recovered.
*
* EVIDENCE: SYSTEM VECTOR
* -----------------------
* CGHDR defines:
*
*          S.COUNT       = 20
*          S.FIN         = 40
*          S.STKCK       = 60
*          S.STKCKCOUNT  = 80
*
* Generated procedure return is:
*
*          BCR 15,11
*
* Generated FINISH is:
*
*          BC  15,40(11)
*
* The vector below therefore has executable branch entries at those
* offsets.  The exact historical bodies are not yet available.
*
* PROCEDURE RETURN CONTRACT
* -------------------------
* Generated entry saves R4..R6 (or more) at 0(R15), then sets R5=R15.
* Calls put the return address in R6.
*
* Test 32 exposed an important distinction in that saved triple:
*
*   0(P)  contains the current procedure's entry/base value in R4
*   4(P)  contains the previous workspace pointer P
*   8(P)  contains the caller return linkage
*
* On return, restoring R4 directly from 0(current P) leaves R4 naming
* the callee.  Generated caller code may immediately use R4 as its own
* base for relative branches.  The correct reconstructed sequence is:
*
*          L    6,8(5)      restore return linkage from callee frame
*          L    5,4(5)      restore caller P
*          L    4,0(5)      restore caller's R4/base from caller frame
*          BCR  15,6
*
* Earlier regressions exercised return control but did not force an
* immediate caller-relative branch after a generated function return.
* Test 32 provides that missing evidence, so the former LM 4,6,0(5)
* implementation is no longer treated as proven.
*
* MACHINE-DEPENDENT GLOBALS KNOWN TO BELONG TO BCPLMAIN
* -----------------------------------------------------
* BLIB explicitly states GETBYTE and PUTBYTE are machine-code routines
* forming part of BCPLMAIN.  Their contracts are known:
*
*   GETBYTE(S,I)       -> byte at offset I from BCPL vector S
*   PUTBYTE(S,I,BYTE)  -> store low 8 bits at byte offset I
*
* BCPL pointers are word pointers; generated string code shifts target
* byte addresses right by two before passing them as BCPL values.
* Implementations below therefore convert S back to a byte address by
* shifting left two.
*
* WRITEF BOOTSTRAP ACCOMMODATION
* ------------------------------
* WRITEF is a BLIB/library routine, not proven to be part of BCPLMAIN.
* Regression 053 begins a narrow bootstrap implementation at G!76.
* The first step copies an ordinary BCPL format string literally to the
* existing SYSPRINT buffer.  Format conversions and newline semantics
* remain future work; this is not claimed as the historical BLIB body.
*
* MVS ENTRY/EXIT
* --------------
* The generated module prefix has already executed the standard:
*
*          STM 14,12,12(13)
*
* before entering BCPLMAIN.  BCPLMAIN now chains a private 18F MVS
* save area before making MVS service calls.  Final return restores the
* caller R13 first, then reloads the saved R14..R12 image.
*
* IMPORTANT UNKNOWN: CGHDR reserves FWSP=96 relative to R13 for
* FIX/FLOAT workspace.  A standard 72-byte caller save area does not
* establish that
* historical contract.  Floating-point generated code is therefore NOT
* supported by this WIP.  A real BCPLMAIN probably establishes its own
* larger R13 work/save area and chains it according to MVS convention.
*
***********************************************************************
* RECONSTRUCTED FINAL BCPLMAIN RESPONSIBILITY CONTRACT
***********************************************************************
*
* This section collects the broader runtime contract recovered from the
* surviving System/370 material.  It is intentionally wider than the
* executable factorial subset below.
*
* Evidence classes used here:
*
*   PROVEN       observed directly in generated code or live probes.
*   HISTORICAL   stated by surviving BCPL source, macros, or build JCL.
*   INFERRED     strongly implied by those sources, not yet exercised.
*   UNKNOWN      facility exists but its interface is incomplete.
*
* BCPLMAIN should eventually satisfy all of these responsibilities.
*
* 1. INITIAL MVS ENTRY AND SAVE-AREA DISCIPLINE
*    HISTORICAL/PROVEN
*
*    Every standard BCPL module begins by saving R14..R12 in the
*    caller's MVS save area, loading BCPLMAIN through module+12, and
*    branching there with R15 still holding the module entry address.
*
*    BCPLMAC's MODULE macro explicitly documents this convention.
*
*    Final BCPLMAIN must establish any private save/work area required
*    beyond the caller's ordinary save area and preserve normal MVS
*    linkage on return.
*
* 2. EXECUTION OPTIONS AND JCL PARM STRING
*    HISTORICAL
*
*    BCPLMAC's INITSAVE layout reserves option fields:
*
*       HNUM  required heap in bytes
*       GNUM  size of global vector
*       KNUM  I/O space to be freed
*       DFLG  STAE/SPIE and related options
*       TNUM  tidy-up time in centiseconds
*       INUM  stack-clearance extent
*
*    The user save area also carries a BCPL parameter string.
*    LIBHDR publishes that string as global G45 PARMS.
*
*    UNKNOWN:
*    The exact textual PARM grammar and defaults still need recovery.
*    No parser should be invented until the historical source is found
*    or the grammar is reconstructed from surviving documentation.
*
* 3. STORAGE ACQUISITION AND INITIAL MEMORY LAYOUT
*    HISTORICAL
*
*    INITSAVE reserves GETMAIN parameter space specifically for the
*    allocation containing the global vector and BCPL stack.
*
*    The user-save-area layout also records:
*
*       a vector-allocation list head for GETVEC/FREEVEC
*       final storage block information for exit cleanup
*       an exit save-area address
*
*    Final BCPLMAIN must therefore own MVS storage acquisition,
*    partition the obtained storage into runtime regions, publish the
*    corresponding BCPL word pointers, and release owned storage.
*
*    The static GLOBV and WORK areas below are development substitutes.
*
* 4. GLOBAL VECTOR CONSTRUCTION
*    PROVEN/HISTORICAL
*
*    R12 is G.  G!N is addressed at byte displacement 4*N.
*
*    BLIB recognizes the uninitialized-global value:
*
*       X'C7D3F000' + 4*N
*
*    G!0 contains the allocated global-vector extent.
*
*    Compiled-module trailers contain exported-global pairs.  BCPLMAIN
*    must merge those definitions into G before invoking START.
*
*    A general loader must perform the same operation for LOAD modules.
*
* 5. STACK / WORKSPACE INITIALIZATION
*    PROVEN/HISTORICAL
*
*    R5 is the current workspace pointer and R15 the next workspace
*    pointer.  Generated calls and entries implement this convention.
*
*    LIBHDR publishes:
*
*       G54 STACKBASE
*       G55 STACKEND
*       G56 STACKHWM
*
*    BLIB knows the historical stack fill patterns:
*
*       X'5C40E2E3'  EVENSTACK
*       X'C3D2405C'  ODDSTACK
*
*    Final startup should initialize whatever marker pattern STACKHWM
*    requires and enforce the stack-clearance policy selected by INUM.
*
* 6. BASE AND PERMANENT REGISTER INITIALIZATION
*    PROVEN
*
*    Generated code assigns:
*
*       R0   permanent zero
*       R1   4096
*       R2   8192
*       R3   12288
*       R11  system-vector base
*       R12  global-vector base
*
*    Job 943 showed why R0 matters: leaving it nonzero defeated a
*    generated comparison against zero and caused runaway recursion.
*
* 7. SYSTEM-VECTOR SERVICES
*    PROVEN/INFERRED
*
*    CGHDR defines executable service offsets:
*
*       +0   procedure return path, reached by BCR 15,11
*       +20  call-count service
*       +40  FINISH
*       +60  stack check
*       +80  stack check plus call count
*
*    The bodies below are proposals or stubs except where noted.
*    Their final semantics must match CG370, not merely factorial.
*
* 8. START INVOCATION AND NORMAL TERMINATION
*    PROVEN/INFERRED
*
*    START is global 1.  Once the runtime environment is complete,
*    BCPLMAIN transfers control to G!1.
*
*    FINISH branches through the system vector at R11+40.
*
*    LIBHDR also exposes G30 STOP.  The relationship among STOP,
*    FINISH, MVS completion codes, cleanup, and return to the caller
*    remains to be reconstructed explicitly.
*
* 9. ABNORMAL TERMINATION AND PROGRAM-INTERRUPT RECOVERY
*    HISTORICAL
*
*    This is a first-class BCPLMAIN responsibility, not an optional
*    diagnostic add-on.
*
*    BCPLMAC contains explicit STAE/SPIE state and support:
*
*       DFLG / USADFLG hold STAE/SPIE options
*       STAESW records an outstanding STAE exit
*       SPIE is identified as SVC 14
*       an STAE execute list is reserved
*       STARETRY reconstructs a saved runtime environment
*       USATCBCC records the task completion-code field
*
*    BLIB supplies high-level:
*
*       ABORT(CODE, ADDR, OLDSTACK, DATA)
*
*    and handles System/360-370 interrupt codes X'C0' through X'CF',
*    user ABENDs, fatal I/O, stack overflow, computation exhaustion,
*    BACKTRACE, USERPOSTMORTEM, and MAPSTORE.
*
*    Therefore final BCPLMAIN must provide the low-level bridge from
*    MVS recovery/program-interrupt state into BLIB's ABORT contract.
*
*    UNKNOWN:
*    The mapping from STAE/SPIE control blocks and saved registers
*    to CODE, ADDR, OLDSTACK, and DATA is not yet reconstructed.
*
*    REQUIRED FUTURE STUB:
*       establish recovery environment
*       capture completion/program-interrupt state
*       restore or identify the BCPL stack
*       invoke G!3 ABORT with the historical four arguments
*       perform final MVS cleanup if ABORT cannot continue
*
* 10. MACHINE-DEPENDENT BYTE OPERATIONS
*     HISTORICAL
*
*    BLIB explicitly states that GETBYTE and PUTBYTE are machine-code
*    routines forming part of BCPLMAIN.  Their contracts are known and
*    provisional implementations are present below.
*
* 11. STREAM, RECORD, DATASET, AND TERMINAL I/O
*     HISTORICAL / INTERFACES PARTLY UNKNOWN
*
*    LIBHDR exposes the native-facing stream surface through G11..G51,
*    including selection, character I/O, record I/O, rewind, member
*    access, parameter input, logging, and terminal discovery.
*
*    BCPLMAC contains substantial DCB, QSAM, BSAM, BPAM, TSO,
*    TPUT/TGET, and device-state definitions.  This confirms that the
*    machine-code library owned real MVS I/O control structures.
*
*    Regression 03 now provides a narrow G14 WRCH path to SYSPRINT.
*    The full selected-stream interface remains unreconstructed.
*    Add other stubs only as their contracts are recovered.
*
* 12. GETVEC / FREEVEC AND STORAGE CLEANUP
*     HISTORICAL / WIP
*
*    LIBHDR assigns G87 GETVEC and G88 FREEVEC.
*    BCPLMAC contains a vector-list head specifically for allocations
*    made by these routines and retains final storage for exit cleanup.
*    BCPLMAC VECAREA describes VECBASE, VECLEN, and VECNEXT.
*
*    Regression 27 adds the first WIP GETVEC success path.  GETVEC(N)
*    obtains N+1 payload words, matching BCPL VEC N.  The WIP block
*    carries a three-word control record before the returned payload:
*
*       +0  VECBASE   BCPL word pointer returned to the caller
*       +4  VECLEN    total bytes obtained from MVS
*       +8  VECNEXT   byte pointer to next allocation record
*       +12 payload   N+1 BCPL words
*
*    VECLIST heads those records.  This is shaped deliberately so that
*    FREEVEC and exit cleanup can be added without replacing GETVEC.
*
*    Regression 28 adds the matching WIP FREEVEC success path.
*    FREEVEC walks VECLIST by VECBASE, unlinks the matching record, and
*    issues FREEMAIN R using the recorded VECLEN and allocation base.
*
*    Regression 30 changes GETVEC to conditional GETMAIN EC and maps
*    allocation failure to BCPL zero.  Negative sizes and arithmetic
*    overflow are rejected before the MVS service call.
*
*    CURRENT LIMITATION:
*    Invalid FREEVEC pointers are currently ignored.  Exact historical
*    invalid-pointer behavior, subpool policy, and RESULT2 interaction
*    remain to be established.
*
* 13. DYNAMIC LOAD / UNLOAD
*     HISTORICAL
*
*    LIBHDR exposes:
*
*       G7  UNLOADALL
*       G8  LOADFORT
*       G9  UNLOAD
*       G10 LOAD
*
*    BLIB's MAPSTORE walks a load list headed through SAVEAREA!29 and
*    recognizes BCPL modules through a high-bit flag in load-list
*    word 9.
*
*    Loaded BCPL sections must have their exported globals merged
*    into G.
*
*    UNKNOWN:
*    loader-node layout and LOAD/UNLOAD arguments/results are not yet
*    complete enough for an implementation.
*
* 14. THE MACHINE-CODE LIBRARY WAS MULTI-MEMBER
*     HISTORICAL
*
*    Surviving MAKELIB JCL says BCPLIB.OBJ(BCPLMAIN) was carved up by
*    the linkage editor to produce:
*
*       $BLOCK$
*       $LOAD$
*       $TPUT$
*       BCPLMAIN
*
*    The library also contained $IOS$, BLIB, and PM as other members.
*
*    This means the final reconstruction should not assume all native
*    services necessarily remain inside one load-module entry point.
*
*    UNKNOWN CONTRACT: $LOAD$
*       Known to be carved from the BCPLMAIN object and included beside
*       BCPLMAIN in the compiler root.  It is clearly related to
*       native loading, but its exact public entry contract is pending.
*
*    UNKNOWN CONTRACT: $BLOCK$
*       Carved from the same object.  Its exact relationship
*       to block-file globals G93..G98 remains to be established.
*
*    UNKNOWN CONTRACT: $TPUT$
*       Known to be carved from the same object.  BCPLMAC defines
*       TPUT/TGET service coding, but its callable interface is
*       still unknown.
*
* 15. PLATFORM EDITING / INSTALLATION VARIANTS
*     HISTORICAL
*
*    EDITMAIN preprocesses the machine-code-library source for:
*
*       OS System/360
*       OS System/370
*       STANDARD, with no OS control-block reference
*       CMS, with no OS control-block reference
*
*    The final MVS 3.8 reconstruction should preserve the distinction
*    between architectural S/370 code and MVS-control-block coupling.
*    Host-specific choices should be documented rather than hidden.
*
* 16. POSTMORTEM AND RUNTIME STATE PUBLISHED TO BLIB
*     HISTORICAL
*
*    BLIB is interdependent with BCPLMAIN.  It expects useful
*    values for SAVEAREA, LOADPOINT, ENDPOINT, STACKBASE, STACKEND,
*    loader state, and program/data extent tests.
*
*    A runtime that merely reaches START but leaves these globals bogus
*    is a bootstrap runtime, not a complete BCPLMAIN reconstruction.
*
* OTHER RUNTIME FACILITIES KNOWN TO EXIST BUT NOT YET RECONSTRUCTED
* -----------------------------------------------------------------
* SYS3 LIBHDR identifies this runtime surface.  Its existence
* is known; this file does not pretend their full interfaces are known
* merely from the global names.
*
*   G2  SETPM
*   G3  ABORT              BLIB supplies high-level reporting; low
*                          program-interrupt capture is still unknown.
*   G4  BACKTRACE
*   G5  ERRORMESSAGE
*   G6  SAVEAREA           this WIP publishes R13>>2 provisionally.
*   G7  UNLOADALL
*   G8  LOADFORT
*   G9  UNLOAD
*   G10 LOAD               segment/module loader contract still
*                          required.
*
*   G11..G26               stream selection and record I/O, including
*                          RDCH, WRCH, READREC, WRITEREC, SKIPREC.
*
*   G27..G39               time/date, STOP, long jump, logging,
*                          and parameter services.
*
*   G40 APTOVEC            allocation primitive.
*   G41..G51               dataset/library/member discovery and close.
*
*   G52 LOADPOINT          published provisionally for main module.
*   G53 ENDPOINT            published provisionally for main module.
*   G54 STACKBASE          published by this WIP.
*   G55 STACKEND           published by this WIP.
*   G56 STACKHWM           BLIB implementation exists; not installed
*                          here.
*   G57 OS/CMS marker      known to exist; exact value convention
*                          pending.
*
*   G58..G84               library helpers, postmortem, FORTRAN bridge,
*                          break/error support.
*
*   G85 GETBYTE            implemented here.
*   G86 PUTBYTE            implemented here.
*   G87..G99               vector allocation, arithmetic, block-file
*                          MOVEBYTES services.
*
* LOAD/UNLOAD deserves its own reconstruction from historical loader
* data.  BLIB shows SAVEAREA!29 as load-list head and tests bit
* X'80000000' in load-list word 9 for BCPL modules.  That is evidence,
* not yet enough
* to implement the loader contract safely.
*
* ---------------------------------------------------------------------
*
BCPLMAIN CSECT
*
* Preserve the compiled-module base before R3 is repurposed as R.K12.
*
         LR    3,15
         BALR  10,0
         USING *,10
         ST    3,MODBASE
*
* Establish a private MVS save area before any service call.
* The generated module prefix already saved the caller's R14..R12.
*
         LA    1,MSVSAVE
         ST    13,4(1)
         ST    1,8(13)
         LR    13,1
*
* Locate L998 = module base + unsigned positive halfword at module+10.
* CG370 limits a generated section to less than 16K bytes, so LH is
* safe.
*
         LH    0,10(3)
         LR    2,3
         AR    2,0
         ST    2,MODEND
*
* Acquire one MVS allocation for G!0..G!699, 16384 usable stack
* words and a provisional 256-byte stack clearance. Preserve the
* tested safe limit while retaining physical headroom above it.
* GETMAIN EC reports failure through R15.
* through R15.  Store base and length for subsequent FREEMAIN R.
*
         L     9,DYNLEN
         GETMAIN EC,LV=(9),A=DYNBASE,SP=0
         LTR   15,15
         BNZ   GNOCORE
         L     12,DYNBASE
         LA    1,GVBYTES(12)
         ST    1,DYNWORK
         A     1,=F'65536'
         ST    1,STKLIM
         A     1,=F'256'
         ST    1,DYNEND
         LA    11,SYSV
*
* Initialize the dynamic global vector with the historical sentinel.
*
         LA    1,GLOBCNT
         ST    1,0(12)
         LA    2,4(12)
         L     3,=X'C7D3F004'
GINIT    ST    3,0(2)
         A     3,=F'4'
         LA    2,4(2)
         BCT   1,GINIT
*
* Find the trailer sentinel by scanning backward in two-word units.
* A pair whose second word is zero is treated as [4*MAXGN,0].
*
         L     8,MODEND
GSCAN    AH    8,=H'-8'
         L     9,4(8)
         LTR   9,9
         BC    7,GSCAN
*
* Reject modules requiring more globals than this static WIP provides.
*
         L     0,0(8)
         C     0,=F'2796'
         BC    2,GTOOBIG
         ST    8,TRAILER
*
* Re-scan from the module end and install each exported global.
*
         L     8,MODEND
GINST    AH    8,=H'-8'
         L     9,4(8)
         LTR   9,9
         BC    8,GIDONE
         L     1,0(8)
         C     1,=F'2796'
         BC    2,GTOOBIG
         LR    2,12
         AR    2,1
         ST    9,0(2)
         BC    15,GINST
*
* G!1 must now contain START rather than the unset sentinel.
*
GIDONE   L     4,4(12)
         C     4,=X'C7D3F004'
         BC    8,NOSTART
*
* Publish the subset of runtime globals whose representation is
* supported strongly enough for this WIP.
*
* G!6 = provisional BCPL word pointer for the current MVS save area.
*
         LR    1,13
         SRL   1,2
         ST    1,24(12)
*
* G!52/G!53 = provisional main-program word-address extent.
*
         L     1,MODBASE
         SRL   1,2
         ST    1,208(12)
         L     1,MODEND
         SRL   1,2
         ST    1,212(12)
*
* G!54/G!55 = BCPL word pointers for the allocated stack extent.
* G!55 includes the reserved clearance; STKLIM is the safe limit.
*
         L     1,DYNWORK
         SRL   1,2
         ST    1,216(12)
         L     1,DYNEND
         SRL   1,2
         ST    1,220(12)
*
* G!14 = first narrow native WRCH implementation for Regression 03.
* G!76 = bootstrap WRITEF, extended through Regression 058.
* G!85/G!86 = machine-dependent byte primitives required by BLIB.
* G!87/G!88 = first WIP GETVEC/FREEVEC dynamic-storage services.
* G!150 = provisional DEBUGINT bootstrap diagnostic service.
*
         LA    1,SELINP
         ST    1,44(12)
         LA    1,RDCHENT
         ST    1,52(12)
         LA    1,UNRDCHEN
         ST    1,60(12)
         LA    1,FINDINP
         ST    1,168(12)
         LA    1,FINDOUT
         ST    1,164(12)
         LA    1,SELOUT
         ST    1,48(12)
         LA    1,ENDWENT
         ST    1,188(12)
         LA    1,ENDRDENT
         ST    1,184(12)
         LA    1,WRCH
         ST    1,56(12)
* Keep BLIB's G!76 WRITEF when its export has been imported.
* Install provisional WRITEST only if G!76 retains the unset sentinel.
         L     1,304(12)
         C     1,=X'C7D3F130'
         BNE   WFHAS76
         LA    1,WRITEST
         ST    1,304(12)
WFHAS76  EQU   *
         LA    1,GETBYTE
         ST    1,340(12)
         LA    1,PUTBYTE
         ST    1,344(12)
         LA    1,GETVEC
         ST    1,348(12)
         LA    1,FREEVEC
         ST    1,352(12)
         LA    1,DEBUGINT
         ST    1,600(12)
         LA    1,APTOVEC
         ST    1,160(12)
         LA    1,STOPENT
         ST    1,120(12)
*
* Regression 03 output is deliberately narrow: one buffered SYSPRINT
* record.  This borrows the proven QSAM shape used by ICINT V19.
*
         XC    OUTPOS(4),OUTPOS
         MVI   OUTBUF,C' '
         MVC   OUTBUF+1(131),OUTBUF
         OPEN  (BCPOUT,(OUTPUT))
         LA    1,OUT1CTL
         SRL   1,2
         ST    1,OUTCURR
*
* Establish S, initial P/W, and the absolute-base constants required by
* generated USING 4096,1,2,3 code.
*
         LA    11,SYSV
         L     15,DYNWORK
         LR    5,15
         L     1,=F'4096'
         L     2,=F'8192'
         L     3,=F'12288'
*
* START receives no arguments.  Clear argument registers and linkage.
* R10 has served as our assembler base and must cease being one now.
*
         SR    6,6
         SR    7,7
         SR    8,8
         SR    9,9
         SR    10,10
*
* Job 943 makes this initialization a required runtime invariant.
*
         SR    0,0
         BCR   15,4
*
* START is expected to terminate through S.FIN.  Returning here is
* treated as a WIP runtime failure.
*
BADRETN  BAL   14,RELMEM
         L     13,4(13)
         LM    14,12,12(13)
         LA    15,36
         BR    14
*
* Bootstrap failures before START.
*
GTOOBIG  BAL   14,RELMEM
         L     13,4(13)
         LM    14,12,12(13)
         LA    15,16
         BR    14
NOSTART  BAL   14,RELMEM
         L     13,4(13)
         LM    14,12,12(13)
         LA    15,20
         BR    14
*
* Failure before allocation: no storage to release.
GNOCORE  L     13,4(13)
         LM    14,12,12(13)
         LA    15,24
         BR    14
*
* Put literals used by startup inside the startup base-register region.
*
         LTORG
*
* From here on R10 is not a runtime base.  Executable system-vector
* services use R11, whose value is SYSV in generated BCPL code.
*
         DROP  10
*
***********************************************************************
* SYSTEM VECTOR
*
* Each public offset is a four-byte branch followed by padding to the
* next 20-byte slot.  This layout is a reconstruction proposal matching
* the offsets in CGHDR; the historical instruction sequence is unknown.
***********************************************************************
SYSV     EQU   *
         USING SYSV,11
         BC    15,RETIMPL
         DS    8H
*
* S.COUNT = 20
*
SYSCOUNT BC    15,CNTIMPL
         DS    8H
*
* S.FIN = 40
*
SYSFIN   BC    15,FINIMPL
         DS    8H
*
* S.STKCK = 60
*
SYSSTK   BC    15,STKIMPL
         DS    8H
*
* S.STKCKCOUNT = 80
*
SYSSTKC  BC    15,STKCIMP
         DS    8H
*
* Runtime-local byte limit and controlled-overflow message.
* Historical BCPLMAC distinguishes STKLIM (safe limit) from STKHIGH.
* This WIP reserves 256 extra bytes above the tested 16KB safe
* limit.  The exact historical INUM interpretation remains unknown.
*
STKLIM   DC    F'0'
STKMSG   DC    CL14'STACK OVERFLOW'
         DS    0H
*
***********************************************************************
* PROCEDURE RETURN
*
* Restore linkage from the callee frame, then restore the caller's P
* before reloading R4 from the caller frame.  Test 32 showed why R4
* cannot be restored from 0(current P): that word names the callee.
***********************************************************************
RETIMPL  L     6,8(5)
         L     5,4(5)
         L     4,0(5)
         BCR   15,6
*
***********************************************************************
* CALL-COUNT SERVICE -- STUB
*
* CG370 emits BAL R14,S.COUNT(R11) followed by an inline fullword.
* A minimally non-destructive stub must skip that word on return.
* Actual counter semantics remain to be reconstructed.
***********************************************************************
CNTIMPL  LA    14,4(14)
         BR    14
*
***********************************************************************
* FINISH
*
* Restore the MVS registers saved by the generated module prefix.
* FINISH selects RC=0; STOP(N) selects the requested step code.
* Both share the output and storage reclamation path.
***********************************************************************
FINIMPL  XC    STOPRC(4),STOPRC
         B     FINEXIT
STOPENT  ST    7,STOPRC
FINEXIT  L     1,OUTPOS
         LTR   1,1
         BZ    FINRETN
         PUT   BCPOUT,OUTBUF
FINRETN  CLOSE (BCPOUT)
         CLI   OUT2OPEN,X'01'
         BNE   FINNOO2
         L     1,OUT2POS
         LTR   1,1
         BZ    FINO2CL
         PUT   BCPOUT2,OUT2BUF
FINO2CL  CLOSE (BCPOUT2)
         MVI   OUT2OPEN,X'00'
FINNOO2  EQU   *
* BCPIN is lazily opened by FINDINPUT; close before task exit.
         CLI   INOPEN,X'01'
         BNE   FINNOIN
         CLOSE (BCPIN)
         MVI   INOPEN,X'00'
FINNOIN  EQU   *
         BAL   14,RELMEM
         L     15,STOPRC
         L     13,4(13)
         LM    14,14,12(13)
         LM    0,12,20(13)
         BR    14
*
* Drain live GETVEC allocations before freeing global/stack memory.
* Each record holds its own byte length and next record address.
* Detach the head before FREEMAIN; never read a released record.
* Save the BAL return across MVS services that may modify R14.
***********************************************************************
RELMEM   ST    14,RELRET
RELLOOP  L     1,VECLIST
         LTR   1,1
         BZ    RELMAIN
         L     10,4(1)
         L     9,8(1)
         ST    9,VECLIST
         FREEMAIN R,LV=(10),A=(1)
         B     RELLOOP
RELMAIN  L     1,DYNBASE
         LTR   1,1
         BZ    RELDONE
         L     10,DYNLEN
         FREEMAIN R,LV=(10),A=(1)
         XC    DYNBASE(4),DYNBASE
RELDONE  L     14,RELRET
         BR    14
*
***********************************************************************
* STACK CHECK -- FRAME-SIZE CONTRACT
*
* Tests 48-49 established the checked-entry sequence and proved that
* this path must perform the LR 5,15 omitted by CG370.
*
* R14 addresses an inline fullword containing the generated frame size
* in bytes.  CG370 has already saved R4-R6 at 0(R15), so R4 is safe as
* a temporary here and can be restored before returning to generated
* code.
*
* Test 50 added structural validation of the inline value.  Test 52
* adds the first WIP limit check: W plus required frame bytes must not
* exceed STKLIM.  BCPLMAC proves that the historical runtime maintained
* a safe stack limit distinct from the byte beyond allocated stack.
* The missing machine-code STKCK body leaves exact clearance semantics
* unrecovered. The provisional boundary remains 16KB from stack base.
***********************************************************************
STKIMPL  LR    5,15
         L     4,0(14)
         LTR   4,4
         BC    12,STKFORM
         TM    3(14),X'03'
         BC    7,STKFORM
         AR    4,15
         C     4,STKLIM
         BH    STKOVFL
         L     4,0(15)
         LA    14,4(14)
         BR    14
STKOVFL  MVC   OUTBUF(14),STKMSG
         LA    4,14
         ST    4,OUTPOS
         B     FINIMPL
STKFORM  L     4,0(15)
         L     13,4(13)
         LM    14,12,12(13)
         LA    15,36
         BR    14
*
***********************************************************************
* STACK CHECK + CALL COUNT -- STUB
*
* CG370 places an inline fullword after this BAL form, so skip it.
***********************************************************************
STKCIMP  LA    14,4(14)
         BR    14
*
***********************************************************************
* APTOVEC -- TEMPORARY STACK VECTOR AND NESTED BCPL CALL
*
* G40 receives F in R7 and N in R8. Supply F(V,N), where V points
* to N+1 BCPL words immediately above APTOVEC's saved linkage.
* Allocate the callee frame above the vector, leaving room for its
* four-register entry save; normal generated stack checks still apply.
* This first rung rejects excessive N and reports stack overflow.
***********************************************************************
APTOVEC  STM   4,6,0(15)
         LR    5,15
         LTR   8,8
         BM    STKOVFL
         C     8,APMAXN
         BH    STKOVFL
         LR    14,8
         SLL   14,2
         LA    14,20(14)
         LR    4,15
         AR    4,14
         LR    14,4
         LA    14,16(14)
         C     14,STKLIM
         BH    STKOVFL
         LR    14,7
         LA    7,16(15)
         SRL   7,2
         LR    15,4
         LR    4,14
         BALR  6,4
* RETIMPL has restored R5 to our frame; R7 holds F's result.
         L     6,8(5)
         L     5,4(5)
         L     4,0(5)
         BCR   15,6
APMAXN   DC    F'16380'
*
***********************************************************************
***********************************************************************
* INPUT STREAM RUNG 094 -- SINGLE NAMED QSAM STREAM BCPIN
*
* FINDINPUT accepts the EBCDIC BCPL string "BCPIN", lazily opens
* its DCB and returns a word-address stream handle. Other DDs fail
* with zero. SELECTINPUT retains that handle. RDCH reads characters
* from an 80-byte fixed QSAM record; end-of-data yields -1.
* This is a bootstrap subset, not multi-stream historical BCPL I/O.
***********************************************************************
FINDINP  STM   0,15,IOSAVE
         LR    14,7
         SLL   14,2
         CLI   0(14),X'05'
         BNE   FNOTFND
         CLC   1(5,14),INNAME
         BNE   FNOTFND
         CLI   INOPEN,X'01'
         BE    FFOUND
         OPEN  (BCPIN,(INPUT))
         MVI   INOPEN,X'01'
         MVI   INEOF,X'00'
         MVI   INNL,X'00'
         MVI   INPUSH,X'00'
         MVI   INSEEN,X'00'
         MVC   INPOS(4),ININIT
FFOUND   LA    7,INCTRL
         SRL   7,2
         B     FRET
FNOTFND  SR    7,7
FRET     ST    7,IORESULT
         LM    0,15,IOSAVE
         L     7,IORESULT
         L     4,0(5)
         BCR   15,6
*
SELINP   LA    14,INCTRL
         SRL   14,2
         CR    7,14
         BNE   SELIRET
         ST    7,INCURR
SELIRET  L     4,0(5)
         BCR   15,6
*
RDCHENT  STM   0,15,IOSAVE
         L     14,INCURR
         LTR   14,14
         BZ    RDEND
         CLI   INPUSH,X'01'
         BE    RDPUSH
         CLI   INEOF,X'01'
         BE    RDEND
         L     14,INPOS
         C     14,INRECLEN
         BL    RDGETCH
         CLI   INNL,X'01'
         BE    RDNEWLN
         GET   BCPIN,INBUF
* Trim fixed-record padding; blanks inside records remain data.
         LA    14,80
         LA    10,INBUF+79
RDTRIM   LTR   14,14
         BZ    RDTRMDN
         CLI   0(10),C' '
         BNE   RDTRMDN
         BCTR  14,0
         BCTR  10,0
         B     RDTRIM
RDTRMDN ST    14,INRECLEN
         XC    INPOS(4),INPOS
         MVI   INNL,X'01'
         LTR   14,14
         BZ    RDNEWLN
         SR    14,14
         B     RDGETCH
RDNEWLN  MVI   INNL,X'00'
         L     14,INRECLEN
         ST    14,INPOS
         LA    7,10
         B     RDRETURN
RDGETCH  LA    10,INBUF
         AR    10,14
         SR    7,7
         IC    7,0(10)
         LA    14,1(14)
         ST    14,INPOS
         B     RDRETURN
RDPUSH   MVI   INPUSH,X'00'
         L     7,INLAST
         B     RDRETURN
RDEND    L     7,INENDVAL
RDRETURN ST    7,IORESULT
         ST    7,INLAST
         MVI   INSEEN,X'01'
         LM    0,15,IOSAVE
         L     7,IORESULT
         L     4,0(5)
         BCR   15,6
*
* UNRDCH repeats the last RDCH result once for this selected stream.
UNRDCHEN CLI   INSEEN,X'01'
         BNE   UNRDRET
         MVI   INPUSH,X'01'
UNRDRET  L     4,0(5)
         BCR   15,6
*
* ENDREAD closes the selected BCPIN input stream and clears state.
ENDRDENT STM   0,15,IOSAVE
         L     14,INCURR
         LTR   14,14
         BZ    ENDRDONE
         CLI   INOPEN,X'01'
         BNE   ENDRCLR
         CLOSE (BCPIN)
         MVI   INOPEN,X'00'
ENDRCLR  XC    INCURR(4),INCURR
         MVI   INEOF,X'00'
         MVI   INNL,X'00'
         MVI   INPUSH,X'00'
         MVI   INSEEN,X'00'
         MVC   INPOS(4),ININIT
ENDRDONE EQU   *
         LM    0,15,IOSAVE
         L     4,0(5)
         BCR   15,6
*
* EODAD receives control from the QSAM GET access method.
INATEND  MVI   INEOF,X'01'
         B     RDEND
*
***********************************************************************
* WRCH -- FIRST NATIVE CHARACTER OUTPUT
*
* G14 WRCH receives the target EBCDIC character in R7.  For the first
* output milestone it appends bytes to one 132-byte SYSPRINT record.
* FINISH writes the buffered record.  Explicit CLOSE is deferred.
* Job 956 showed the first WIP CLOSE path looping until S322.
* Newline and general stream semantics remain future work.
*
* No MVS macro I/O occurs inside WRCH.
*
* Job 960 established an additional machine-routine return contract:
* generated code may branch relative to R4 immediately after a call.
* Procedure entry saved the caller B value at 0(R5).
* Native primitives restore R4 from that slot before returning via R6.
* R0 and R1-R3 are permanent generated-code registers.
* Native primitives preserve them.
***********************************************************************
WRCH     L     14,OUTCURR
         LA    4,OUT2CTL
         SRL   4,2
         CR    14,4
         BE    WROUT2
         L     14,OUTPOS
         LA    4,132
         CR    14,4
         BNL   WRCHRTN
         LA    4,OUTBUF
         AR    4,14
         STC   7,0(4)
         LA    14,1(14)
         ST    14,OUTPOS
WRCHRTN  L     4,0(5)
         BCR   15,6
*
***********************************************************************
*
* Separate named output DCB, simultaneous with default SYSPRINT.
* This first implementation uses one static BCPL descriptor per DD.
* Preserve R0-R3, R5, R6, R15 across QSAM services.
FINDOUT  STM   0,15,OUTSVREG
         LR    14,7
         SLL   14,2
         CLI   0(14),X'06'
         BNE   FONOTFD
         CLC   1(6,14),OUT2NAME
         BNE   FONOTFD
         CLI   OUT2OPEN,X'01'
         BE    FOGOT
         OPEN  (BCPOUT2,(OUTPUT))
         MVI   OUT2OPEN,X'01'
         XC    OUT2POS(4),OUT2POS
         MVI   OUT2BUF,C' '
         MVC   OUT2BUF+1(131),OUT2BUF
FOGOT    LA    7,OUT2CTL
         SRL   7,2
         B     FORET
FONOTFD  SR    7,7
FORET    ST    7,OUTRESULT
         LM    0,15,OUTSVREG
         L     7,OUTRESULT
         L     4,0(5)
         BCR   15,6
*
SELOUT   LA    14,OUT2CTL
         SRL   14,2
         CR    7,14
         BE    SO2
         LA    14,OUT1CTL
         SRL   14,2
         CR    7,14
         BNE   SOR
SO2      ST    7,OUTCURR
SOR      L     4,0(5)
         BCR   15,6
*
* Selected BCPALT path. A BCPL newline ends one QSAM record.
* The 132-byte buffer is reset to blank after each PUT.
WROUT2   STM   0,15,OUTSVREG
         C     7,OUTLF
         BE    WO2PUT
         L     14,OUT2POS
         C     14,OUTMAX
         BNL   WO2RET
         LA    4,OUT2BUF
         AR    4,14
         STC   7,0(4)
         LA    14,1(14)
         ST    14,OUT2POS
         B     WO2RET
WO2PUT   PUT   BCPOUT2,OUT2BUF
         XC    OUT2POS(4),OUT2POS
         MVI   OUT2BUF,C' '
         MVC   OUT2BUF+1(131),OUT2BUF
WO2RET   LM    0,15,OUTSVREG
         L     4,0(5)
         BCR   15,6
*
* Explicit close of selected named output. Default SYSPRINT continues
* through the existing FINISH-owned path.
ENDWENT  STM   0,15,OUTSVREG
         L     14,OUTCURR
         LA    4,OUT2CTL
         SRL   4,2
         CR    14,4
         BNE   EWRETURN
         CLI   OUT2OPEN,X'01'
         BNE   EWCLEAR
         L     1,OUT2POS
         LTR   1,1
         BZ    EWCLOSE
         PUT   BCPOUT2,OUT2BUF
EWCLOSE  CLOSE (BCPOUT2)
         MVI   OUT2OPEN,X'00'
EWCLEAR  LA    14,OUT1CTL
         SRL   14,2
         ST    14,OUTCURR
EWRETURN LM    0,15,OUTSVREG
         L     4,0(5)
         BCR   15,6
*
* WRITEF -- LITERAL + %N/%C/%S/%I/%X/%O BOOTSTRAP
*
* Regression 053 established literal-string output through G76.
* Regression 054 adds the historical BLIB %N case: decimal output of
* the next argument with no width field.  Regression 055 adds %C and
* %S and proves sequential consumption of R8 then R9. Regression 056
* adds the historical %I width path; Test 060 adds A-F width digits.
*
* BCPL strings use a length byte at byte offset zero followed by data
* bytes.  Literal bytes are copied to OUTBUF.  A '%' followed by 'N'
* emits signed decimal; %C emits one character; %S emits a BCPL
* string; %I consumes one width character and emits signed decimal
* right-justified in that field. %X and %O consume one width
* character and emit exactly that many zero-filled hexadecimal or
* octal digits respectively.
*
* This is bootstrap machinery, not a reconstruction of BLIB's BCPL
* WRITEF body.  R0 and R1-R3 remain permanent generated-code registers.
***********************************************************************
WRITEST  STM   2,6,WFREGSV
         ST    8,WFARGS
         ST    9,WFARGS+4
         XC    WFARGIX(4),WFARGIX
         LR    14,7
         SLL   14,2
         SR    8,8
         IC    8,0(14)
         LA    14,1(14)
         L     9,OUTPOS
WFLITLP  LTR   8,8
         BZ    WFLITDN
         SR    7,7
         IC    7,0(14)
         CLI   0(14),C'%'
         BNE   WFLITCP
         LA    4,2
         CR    8,4
         BL    WFLITCP
         CLI   1(14),C'N'
         BE    WFNSEL
         CLI   1(14),C'C'
         BE    WFCSEL
         CLI   1(14),C'I'
         BE    WFISEL
         CLI   1(14),C'X'
         BE    WFXSEL
         CLI   1(14),C'O'
         BE    WFOSEL
         CLI   1(14),C'S'
         BE    WFSTSEL
         CLI   1(14),C'$'
         BE    WFSKARG
         B     WFUNK
WFSTSEL  EQU   *
         LA    14,2(14)
         SR    8,4
         BAL   10,WFNEXT
         B     WFSTR
*
* Historical BLIB default emits the unknown conversion character
* without the '%' and without advancing the argument cursor.
*
*
* Historical BLIB percent-dollar skips one argument; emits nothing.
*
WFSKARG  L     6,WFARGIX
         LA    6,1(6)
         ST    6,WFARGIX
         LA    14,2(14)
         SR    8,4
         B     WFLITLP
WFUNK    SR    7,7
         IC    7,1(14)
         LA    14,2(14)
         SR    8,4
         BAL   10,WFPUTC
         B     WFLITLP
WFNSEL   XC    WFWIDTH(4),WFWIDTH
         LA    14,2(14)
         SR    8,4
         BAL   10,WFNEXT
         B     WFNUM
WFISEL  LA    5,3
         CR    8,5
         BL    WFLITCP
         SR    6,6
         IC    6,2(14)
         CLI   2(14),C'A'
         BL    WFIDEC
         CLI   2(14),C'F'
         BH    WFIDEC
         S     6,WFHEXAO
         B     WFISTOR
WFIDEC   S     6,WFZERO
WFISTOR  ST    6,WFWIDTH
         LA    14,3(14)
         SR    8,5
         BAL   10,WFNEXT
         B     WFNUM
WFXSEL   LA    5,3
         CR    8,5
         BL    WFLITCP
         SR    6,6
         IC    6,2(14)
         CLI   2(14),C'A'
         BL    WFXDEC
         CLI   2(14),C'F'
         BH    WFXDEC
         S     6,WFHEXAO
         B     WFXSTOR
WFXDEC   S     6,WFZERO
WFXSTOR  ST    6,WFWIDTH
         LA    14,3(14)
         SR    8,5
         BAL   10,WFNEXT
         B     WFHEX
WFOSEL   LA    5,3
         CR    8,5
         BL    WFLITCP
         SR    6,6
         IC    6,2(14)
         CLI   2(14),C'A'
         BL    WFODEC
         CLI   2(14),C'F'
         BH    WFODEC
         S     6,WFHEXAO
         B     WFOSTOR
WFODEC   S     6,WFZERO
WFOSTOR  ST    6,WFWIDTH
         LA    14,3(14)
         SR    8,5
         BAL   10,WFNEXT
         B     WFOCT
WFCSEL   LA    14,2(14)
         SR    8,4
         BAL   10,WFNEXT
         BAL   10,WFPUTC
         B     WFLITLP
WFLITCP  LA    14,1(14)
         BCTR  8,0
         BAL   10,WFPUTC
         B     WFLITLP
*
* Emit the current signed integer using the proven CVD/UNPK shape
* used by DEBUGINT, then copy digits through the common byte appender.
*
WFNUM    ST    8,WFREM
         ST    14,WFFMTP
         XC    WFSIGN(4),WFSIGN
         LTR   7,7
         BNM   WFCVT
         LA    6,1
         ST    6,WFSIGN
WFCVT    CVD   7,WFDECPK
         UNPK  WFDECZN(15),WFDECPK(8)
         OI    WFDECZN+14,X'F0'
         LA    4,WFDECZN
         LA    5,15
WFSKIP   CLI   0(4),C'0'
         BNE   WFPAD
         LA    6,1
         CR    5,6
         BE    WFPAD
         LA    4,1(4)
         BCT   5,WFSKIP
*
* R5 is now the digit count.  Pad on the left to WFWIDTH, counting a
* minus sign as part of the field.  A width of zero is the %N case.
*
WFPAD    L     2,WFWIDTH
         LTR   2,2
         BZ    WFSIGNO
         SR    2,5
         S     2,WFSIGN
         BNP   WFSIGNO
WFPADLP  LA    7,64
         BAL   10,WFPUTC
         BCT   2,WFPADLP
WFSIGNO  L     6,WFSIGN
         LTR   6,6
         BZ    WFDCOPY
         LA    7,96
         BAL   10,WFPUTC
WFDCOPY  SR    7,7
         IC    7,0(4)
         BAL   10,WFPUTC
         LA    4,1(4)
         BCT   5,WFDCOPY
         L     8,WFREM
         L     14,WFFMTP
         B     WFLITLP
*
* Emit exactly WFWIDTH hexadecimal digits from the current argument.
* This mirrors historical WRITEHEX: fixed width, zero filled, high
* nibbles first. Regression 057 establishes width 4.
*
WFHEX    ST    8,WFREM
         ST    14,WFFMTP
         ST    7,WFHEXVAL
         L     5,WFWIDTH
         LTR   5,5
         BZ    WFHEXDN
         LR    2,5
         BCTR  2,0
         SLL   2,2
WFHEXLP  L     7,WFHEXVAL
         SRL   7,0(2)
         N     7,WFHEXMSK
         C     7,WFHEXNIN
         BL    WFHEXDIG
         A     7,WFHEXAO
         B     WFHEXOUT
WFHEXDIG A     7,WFHEXZO
WFHEXOUT BAL   10,WFPUTC
         SH    2,WFHXFOUR
         BCT   5,WFHEXLP
WFHEXDN  L     8,WFREM
         L     14,WFFMTP
         B     WFLITLP
*
* Emit exactly WFWIDTH octal digits from the current argument.
* This mirrors historical WRITEOCT: fixed width, zero filled, high
* 3-bit groups first. Regression 058 establishes width 4.
*
WFOCT    ST    8,WFREM
         ST    14,WFFMTP
         ST    7,WFOCTVAL
         L     5,WFWIDTH
         LTR   5,5
         BZ    WFOCTDN
         LR    2,5
         BCTR  2,0
         LR    6,2
         SLL   2,1
         AR    2,6
WFOCTLP  L     7,WFOCTVAL
         SRL   7,0(2)
         N     7,WFOCTMSK
         A     7,WFHEXZO
         BAL   10,WFPUTC
         SH    2,WFOCTTHR
         BCT   5,WFOCTLP
WFOCTDN  L     8,WFREM
         L     14,WFFMTP
         B     WFLITLP
*
* Emit a BCPL string argument in R7.  Preserve the format cursor and
* remaining format length in R14/R8 while the string bytes are copied.
*
WFSTR    LR    4,7
         SLL   4,2
         SR    5,5
         IC    5,0(4)
         LA    4,1(4)
WFSTRLP  LTR   5,5
         BZ    WFLITLP
         SR    7,7
         IC    7,0(4)
         BAL   10,WFPUTC
         LA    4,1(4)
         BCTR  5,0
         B     WFSTRLP
*
* Fetch the next saved formatting argument into R7 and advance the
* bootstrap argument cursor.  Test 055 exercises R8 then R9.
*
WFNEXT   L     6,WFARGIX
         SLL   6,2
         LA    4,WFARGS
         AR    4,6
         L     7,0(4)
         L     6,WFARGIX
         LA    6,1(6)
         ST    6,WFARGIX
         BR    10
*
* Reload the argument most recently returned by WFNEXT.  The negative
* sign append in WFNUM temporarily consumes R7.
*
WFLAST   L     6,WFARGIX
         BCTR  6,0
         SLL   6,2
         LA    4,WFARGS
         AR    4,6
         L     7,0(4)
         BR    10
*
* Append R7 low byte to OUTBUF when room remains.  R9 is OUTPOS.
* Return through R10, which is scratch for this bootstrap WRITEF.
*
WFPUTC   LA    6,132
         CR    9,6
         BNL   WFPUTRT
         LA    6,OUTBUF
         AR    6,9
         STC   7,0(6)
         LA    9,1(9)
WFPUTRT  BR    10
WFLITDN  ST    9,OUTPOS
         LM    2,6,WFREGSV
         L     4,0(5)
         BCR   15,6
*
WFREGSV  DS    5F
WFARGS   DS    2F
WFARGIX  DC    F'0'
WFWIDTH  DC    F'0'
WFSIGN   DC    F'0'
WFZERO   DC    X'000000F0'
WFHEXMSK DC    F'15'
WFHEXNIN DC    F'10'
WFHEXAO  DC    F'183'
WFHEXZO  DC    F'240'
WFHXFOUR DC   H'4'
WFHEXVAL DC    F'0'
WFOCTMSK DC    F'7'
WFOCTTHR DC    H'3'
WFOCTVAL DC    F'0'
WFREM    DC    F'0'
WFFMTP   DC    A(0)
WFDECPK  DS    D
WFDECZN  DS    CL15
*
***********************************************************************
* GETBYTE(S,I) -> R7
*
* S is a BCPL word pointer.  I is an unrestricted byte offset.
***********************************************************************
GETBYTE  LR    14,7
         SLL   14,2
         AR    14,8
         SR    7,7
         IC    7,0(14)
         L     4,0(5)
         BCR   15,6
*
***********************************************************************
* PUTBYTE(S,I,BYTE)
*
* S in R7, I in R8, BYTE in R9.  Store the low eight bits.
***********************************************************************
PUTBYTE  LR    14,7
         SLL   14,2
         AR    14,8
         STC   9,0(14)
         L     4,0(5)
         BCR   15,6
*
***********************************************************************
* GETVEC(N) -> R7 -- WIP DYNAMIC STORAGE
*
* Regression 27 success-path implementation.
*
* BCPL VEC N has indices 0..N, so GETVEC(N) supplies N+1 payload
* fullwords.  Twelve private bytes precede the payload and mirror the
* historical VECAREA fields VECBASE, VECLEN, and VECNEXT.
*
* Regression 30 changes allocation to conditional GETMAIN EC.
* GETVEC returns zero for a negative or overlarge size, or an MVS
* allocation failure.  N<=4194299 keeps the byte count within 24 bits.
*
* GETMAIN EC returns its address through A= and completion in R15.
* Generated BCPL requires R0=0 and R1-R3 to hold permanent constants,
* R5 to remain P, R6 to remain L, and R15 to remain W.  Preserve them
* explicitly across the MVS service as defensive runtime discipline.
* Test 32 ultimately identified a separate RETIMPL error, not GETMAIN
* register corruption.
***********************************************************************
GETVEC   LTR   7,7
         BC    4,GVFAIL0
         C     7,GVRMAX
         BC    2,GVFAIL0
         STM   0,3,GVRSAVE
         ST    5,GVRPSAVE
         ST    6,GVRLSAVE
         ST    15,GVRWSAVE
         LR    10,7
         LA    10,1(10)
         SLL   10,2
         LA    10,12(10)
         ST    10,GVRLEN
         GETMAIN EC,LV=(10),A=GVRADDR,SP=0
         LTR   15,15
         BNZ   GVFAIL
*
* EC writes the allocated byte address at GVRADDR.  Build the WIP
* VECAREA record in the allocated block and chain it at VECLIST.
*
         L     14,GVRADDR
         LA    7,12(14)
         SRL   7,2
         ST    7,0(14)
         L     10,GVRLEN
         ST    10,4(14)
         L     10,VECLIST
         ST    10,8(14)
         ST    14,VECLIST
*
* Restore permanent generated-code registers and W.  R7 deliberately
* retains the BCPL word pointer result.
*
         L     15,GVRWSAVE
         LM    0,3,GVRSAVE
         L     5,GVRPSAVE
         L     6,GVRLSAVE
         L     4,0(5)
         BCR   15,6
*
* Failure after register save.  Return the BCPL failure value zero.
*
GVFAIL   L     15,GVRWSAVE
         LM    0,3,GVRSAVE
         L     5,GVRPSAVE
         L     6,GVRLSAVE
GVFAIL0  SR    7,7
         L     4,0(5)
         BCR   15,6
*
***********************************************************************
* FREEVEC(V) -- WIP DYNAMIC STORAGE RELEASE
*
* Regression 28 success-path implementation.
*
* V is the BCPL word pointer returned by GETVEC.  Walk VECLIST looking
* for a control record whose VECBASE field matches V.  Unlink that
* record, then release exactly the recorded MVS allocation.
*
* This first rung treats V=0 or an unknown pointer as a no-op.  The
* historical error contract for invalid FREEVEC arguments is not yet
* reconstructed.
*
* FREEMAIN R may disturb the machine-service register set.  Preserve
* R0-R3 because generated code requires them, R5/R6 because they are
* BCPL P/L, and R15 because it is W.  This is defensive runtime
* discipline; Test 32 ultimately identified a separate RETIMPL error.
***********************************************************************
FREEVEC  LTR   7,7
         BZ    FVRETURN
         STM   0,3,FVRSAVE
         ST    5,FVPSAVE
         ST    6,FVLSAVE
         ST    15,FVWSAVE
         LR    9,7
         SR    8,8
         L     14,VECLIST
FVSCAN   LTR   14,14
         BZ    FVNFOUND
         C     9,0(14)
         BE    FVFOUND
         LR    8,14
         L     14,8(14)
         B     FVSCAN
*
* R14 = matching allocation record; R8 = previous record or zero.
*
FVFOUND  L     10,8(14)
         LTR   8,8
         BZ    FVHEAD
         ST    10,8(8)
         B     FVUNLNK
FVHEAD   ST    10,VECLIST
FVUNLNK  L     10,4(14)
         LR    1,14
         FREEMAIN R,LV=(10),A=(1)
         L     15,FVWSAVE
         LM    0,3,FVRSAVE
         L     5,FVPSAVE
         L     6,FVLSAVE
FVRETURN L     4,0(5)
         BCR   15,6
*
* Unknown nonzero pointer: restore the saved permanent registers.
*
FVNFOUND L     15,FVWSAVE
         LM    0,3,FVRSAVE
         L     5,FVPSAVE
         L     6,FVLSAVE
         B     FVRETURN
*
***********************************************************************
* DEBUGINT -- PROVISIONAL BOOTSTRAP DIAGNOSTIC
*
* G150 DEBUGINT receives a signed 32-bit integer in R7.
* It appends decimal text to the same SYSPRINT record used by WRCH.
* This is not a recovered historical BCPL library interface.
* It must not be confused with WRITEN or WRITEF.
*
* CVD creates packed decimal and UNPK creates zoned digits.
* The final zone is normalized after the sign nibble is consumed.
* Leading zeroes are suppressed.  Zero itself emits one digit.
***********************************************************************
DEBUGINT LTR   7,7
         BNM   DBGCVT
         LA    10,C'-'
         BAL   14,DBGAPND
DBGCVT   CVD   7,DECPACK
         UNPK  DECZON(15),DECPACK(8)
         OI    DECZON+14,X'F0'
         LA    8,DECZON
         LA    9,15
DBGSKIP  CLI   0(8),C'0'
         BNE   DBGOUT
         LA    4,1
         CR    9,4
         BE    DBGOUT
         LA    8,1(8)
         BCT   9,DBGSKIP
DBGOUT   SR    10,10
         IC    10,0(8)
         BAL   14,DBGAPND
         LA    8,1(8)
         BCT   9,DBGOUT
         L     4,0(5)
         BCR   15,6
*
* Append one EBCDIC byte from R10.  R14 is local linkage.
*
DBGAPND  L     4,OUTPOS
         LA    7,132
         CR    4,7
         BNL   DBGARET
         LA    7,OUTBUF
         AR    7,4
         STC   10,0(7)
         LA    4,1(4)
         ST    4,OUTPOS
DBGARET  BR    14
*
***********************************************************************
***********************************************************************
* WIP DATA
***********************************************************************
         DS    0F
MODBASE  DC    F'0'
MODEND   DC    F'0'
TRAILER  DC    F'0'
*
* GETVEC WIP allocation state.
* VECLIST is a byte pointer to the first three-word control record.
*
VECLIST  DC    F'0'
GVRMAX   DC    F'4194299'
GVRLEN   DC    F'0'
GVRADDR  DC    F'0'
GVRSAVE  DS    4F
GVRPSAVE DC    F'0'
GVRLSAVE DC    F'0'
GVRWSAVE DC    F'0'
FVRSAVE  DS    4F
FVPSAVE  DC    F'0'
FVLSAVE  DC    F'0'
FVWSAVE  DC    F'0'
*
* Private MVS save area used while BCPLMAIN owns R13.
*
MSVSAVE  DS    18F
*
* Contiguous GETMAIN layout: 700 global fullwords, 16384 stack
* fullwords, and 256 bytes of provisional clearance.  Dynamic backing
* addresses are saved in static controls.
* The GETMAIN block is released as a unit during FINISH/error exit.
*
GLOBCNT  EQU   699
GVBYTES  EQU   (GLOBCNT+1)*4
DYNLEN   DC    F'68592'
DYNBASE  DC    F'0'
DYNWORK  DC    F'0'
DYNEND   DC    F'0'
RELRET   DC    F'0'
STOPRC   DC    F'0'
*
* Regression 03 output state.  SYSPRINT is supplied by the GO step.
* Historical stream/DCB support was richer; this is only the first
* observable character-output rung.  Normal step termination currently
* owns DCB cleanup; explicit CLOSE remains under reconstruction.
*
DECPACK  DS    D
DECZON   DS    CL15
OUTPOS   DC    F'0'
OUTBUF   DS    CL132
BCPOUT   DCB   DDNAME=SYSPRINT,DSORG=PS,MACRF=PM
*
*
* Two simultaneously open logical output destinations (SYSPRINT,
* BCPALT). The second DCB is explicitly supplied by regression JCL.
         DS    0F
OUT1CTL  DC    F'1'
OUT2CTL  DC    F'2'
OUTCURR  DC    F'0'
OUTRESULT DC   F'0'
OUT2POS  DC    F'0'
OUTMAX   DC    F'132'
OUTLF    DC    F'10'
OUT2NAME DC    CL6'BCPALT'
OUT2OPEN DC    X'00'
         DS    0F
OUTSVREG DS    16F
OUT2BUF  DS    CL132
BCPOUT2  DCB   DDNAME=BCPALT,DSORG=PS,MACRF=PM
*
* One-stream bootstrap input controls for native regression 094.
         DS    0F
INCTRL   DC    F'1'
INCURR DC   F'0'
INRECLEN DC    F'80'
INNL     DC    X'00'
INPUSH   DC    X'00'
INSEEN   DC    X'00'
         DS    0F
INLAST   DC    F'0'
INENDVAL DC    F'-1'
INPOS    DC    F'80'
ININIT   DC    F'80'
INNAME   DC    CL5'BCPIN'
INOPEN   DC    X'00'
INEOF    DC    X'00'
         DS    0F
IORESULT DC    F'0'
IOSAVE   DS    16F
INBUF    DS    CL80
BCPIN    DCB   DDNAME=BCPIN,DSORG=PS,MACRF=GM,EODAD=INATEND

*
* Stack marker initialization and historical clearance remain separate
* work.  No static workspace is reserved in this CSECT.
*
         END   BCPLMAIN
