*
* BCPLMAIN-WIP.ASM
*
* Working reconstruction proposal for the native IBM System/370 BCPL
* runtime entry expected by the surviving Cambridge CG370.
*
* STATUS
* ------
* This is deliberately a WIP, not a claim to be historical BCPLMAIN.
* Code is present where the project has direct evidence or a narrow,
* testable inference.  Missing runtime facilities are called out below.
*
* PRIMARY CURRENT MILESTONE
* -------------------------
* Supply enough of the native runtime contract to execute the Richards
* factorial test generated by the Cambridge compiler, while preserving
* the shape needed for a fuller reconstruction.
*
* EVIDENCE: COMPILED-MODULE ENTRY
* -------------------------------
* Generated modules begin:
*
*          STM 14,12,12(13)
*          L   4,12(15)
*          BCR 15,4
*          DC  AL2(L998-L999)
*          DC  A(BCPLMAIN)
*
* Job 940 established that BCPLMAIN receives control with
* R15 still equal to the generated module base.
*
* The halfword at module+10 is the byte length from L999 to L998.
*
* EVIDENCE: GLOBAL TRAILER
* ------------------------
* CGGLOBAL emits, immediately before L998:
*
*          DC F'4*MAXGN'
*          DC F'0'
*          repeated:
*              DC F'4*GLOBAL-NUMBER'
*              DC A(GLOBAL-ADDRESS)
*
* Job 941 established that the factorial module can be decoded through
* this structure and that its final pair is G!1 = START.
*
* The generic backward scan below is a reconstruction proposal.  It
* relies on the zero address word preceding the exported-global pairs.
* It is not yet validated with a module exporting several globals.
*
* EVIDENCE: GENERATED REGISTER CONTRACT
* -------------------------------------
* From CGHDR:
*
*   R1   R.K4   expected constant 4096
*   R2   R.K8   expected constant 8192
*   R3   R.K12  expected constant 12288
*   R4   R.B    branch/callee address
*   R5   R.P    current BCPL workspace pointer
*   R6   R.L    BCPL linkage register
*   R7   R.A1   argument 1 / function result
*   R8   R.A2   argument 2
*   R9   R.A3   argument 3
*   R10  R.A4   argument 4
*   R11  R.S    system-vector base
*   R12  R.G    global-vector base
*   R14  R.A    compiler scratch/linkage register
*   R15  R.W    new-workspace pointer
*
* LIVE ARGUMENT-LINKAGE EVIDENCE
* ------------------------------
* Native regression Tests 11-14 now confirm the generated call-time
* argument convention, not merely the symbolic register names in CGHDR.
*
* Job 986 (Test 11) proved argument 1 is passed in R7.
* Job 990 (Test 13) proved:
*
*          argument 1 -> R7
*          argument 2 -> R8
*
* Job 992 (Test 14) proved:
*
*          argument 1 -> R7
*          argument 2 -> R8
*          argument 3 -> R9
*
* In Test 14 the caller loaded V, I, X into R7, R8, R9 immediately
* before BALR.  The generated three-argument callee began:
*
*          STM 4,9,0(15)
*          LR  5,15
*
* and then used R7/R8 to form V!I while storing R9 through the
* computed address.  This is direct executable evidence for native
* machine-code runtime entries such as PUTBYTE(S,I,BYTE): their first
* three BCPL arguments arrive in R7, R8, and R9 respectively.
*
* Generated text also says:
*
*          USING 4096,1,2,3
*
* so a general runtime must establish R1/R2/R3, even though the first
* factorial module does not use them.
*
* NEW EVIDENCE FROM JOB 943: R0 MUST BE ZERO
* ------------------------------------------
* The factorial function tests its base case using:
*
*          CR 7,0
*
* Our first native-runtime probe left R0 holding the WRITEF address.
* Recursion therefore passed through N=0.  At the S0C4, R7 was -61,
* R15 had reached the end of the temporary workspace, and the failing
* instruction was the recursive-entry STM at module offset X'4C'.
*
* The startup below therefore establishes R0=0 immediately before
* entering BCPL code.  Runtime primitives must preserve that invariant.
*
* EVIDENCE: GLOBAL VECTOR
* -----------------------
* Generated WRITEF call:
*
*          L    4,304(12)
*          BALR 6,4
*
* proves R12 is G and global N is at byte displacement 4*N.
*
* BLIB expects G!0 to describe the allocated global-vector extent and
* recognizes an uninitialized global sentinel:
*
*          X'C7D3F000' + 4*N
*
* This WIP allocates a modest static global-vector extent.
* It initializes the historical sentinel convention.
* Dynamic sizing/GETMAIN remains to be recovered.
*
* EVIDENCE: SYSTEM VECTOR
* -----------------------
* CGHDR defines:
*
*          S.COUNT       = 20
*          S.FIN         = 40
*          S.STKCK       = 60
*          S.STKCKCOUNT  = 80
*
* Generated procedure return is:
*
*          BCR 15,11
*
* Generated FINISH is:
*
*          BC  15,40(11)
*
* The vector below therefore has executable branch entries at those
* offsets.  The exact historical bodies are not yet available.
*
* PROCEDURE RETURN CONTRACT
* -------------------------
* Generated entry saves R4..R6 (or more) at 0(R15), then sets R5=R15.
* Calls put the return address in R6.  The return trampoline:
*
*          LM   4,6,0(5)
*          BCR  15,6
*
* restores callee address, previous P, and linkage, then returns.
* Successful native procedure-call regressions, including Tests 01,
* 11, 12, 13, and 14, have exercised this return path.  It is now
* treated as PROVEN for ordinary generated BCPL procedure linkage.
*
* MACHINE-DEPENDENT GLOBALS KNOWN TO BELONG TO BCPLMAIN
* -----------------------------------------------------
* BLIB explicitly states GETBYTE and PUTBYTE are machine-code routines
* forming part of BCPLMAIN.  Their contracts are known:
*
*   GETBYTE(S,I)       -> byte at offset I from BCPL vector S
*   PUTBYTE(S,I,BYTE)  -> store low 8 bits at byte offset I
*
* BCPL pointers are word pointers; generated string code shifts target
* byte addresses right by two before passing them as BCPL values.
* Implementations below therefore convert S back to a byte address by
* shifting left two.
*
* FACTORIAL-ONLY ACCOMMODATION
* ----------------------------
* WRITEF is a BLIB/library routine, not proven to be part of BCPLMAIN.
* Until BLIB is linked natively, G!76 is installed as a no-op stub so
* the factorial control-flow test can run.  This must not survive as
* the final WRITEF implementation.
*
* MVS ENTRY/EXIT
* --------------
* The generated module prefix has already executed the standard:
*
*          STM 14,12,12(13)
*
* before entering BCPLMAIN.  BCPLMAIN now chains a private 18F MVS
* save area before making MVS service calls.  Final return restores the
* caller R13 first, then reloads the saved R14..R12 image.
*
* IMPORTANT UNKNOWN: CGHDR reserves FWSP=96 relative to R13 for
* FIX/FLOAT workspace.  A standard 72-byte caller save area does not
* establish that
* historical contract.  Floating-point generated code is therefore NOT
* supported by this WIP.  A real BCPLMAIN probably establishes its own
* larger R13 work/save area and chains it according to MVS convention.
*
***********************************************************************
* RECONSTRUCTED FINAL BCPLMAIN RESPONSIBILITY CONTRACT
***********************************************************************
*
* This section collects the broader runtime contract recovered from the
* surviving System/370 material.  It is intentionally wider than the
* executable factorial subset below.
*
* Evidence classes used here:
*
*   PROVEN       observed directly in generated code or live probes.
*   HISTORICAL   stated by surviving BCPL source, macros, or build JCL.
*   INFERRED     strongly implied by those sources, not yet exercised.
*   UNKNOWN      facility exists but its interface is incomplete.
*
* BCPLMAIN should eventually satisfy all of these responsibilities.
*
* 1. INITIAL MVS ENTRY AND SAVE-AREA DISCIPLINE
*    HISTORICAL/PROVEN
*
*    Every standard BCPL module begins by saving R14..R12 in the
*    caller's MVS save area, loading BCPLMAIN through module+12, and
*    branching there with R15 still holding the module entry address.
*
*    BCPLMAC's MODULE macro explicitly documents this convention.
*
*    Final BCPLMAIN must establish any private save/work area required
*    beyond the caller's ordinary save area and preserve normal MVS
*    linkage on return.
*
* 2. EXECUTION OPTIONS AND JCL PARM STRING
*    HISTORICAL
*
*    BCPLMAC's INITSAVE layout reserves option fields:
*
*       HNUM  required heap in bytes
*       GNUM  size of global vector
*       KNUM  I/O space to be freed
*       DFLG  STAE/SPIE and related options
*       TNUM  tidy-up time in centiseconds
*       INUM  stack-clearance extent
*
*    The user save area also carries a BCPL parameter string.
*    LIBHDR publishes that string as global G45 PARMS.
*
*    UNKNOWN:
*    The exact textual PARM grammar and defaults still need recovery.
*    No parser should be invented until the historical source is found
*    or the grammar is reconstructed from surviving documentation.
*
* 3. STORAGE ACQUISITION AND INITIAL MEMORY LAYOUT
*    HISTORICAL
*
*    INITSAVE reserves GETMAIN parameter space specifically for the
*    allocation containing the global vector and BCPL stack.
*
*    The user-save-area layout also records:
*
*       a vector-allocation list head for GETVEC/FREEVEC
*       final storage block information for exit cleanup
*       an exit save-area address
*
*    Final BCPLMAIN must therefore own MVS storage acquisition,
*    partition the obtained storage into runtime regions, publish the
*    corresponding BCPL word pointers, and release owned storage.
*
*    The static GLOBV and WORK areas below are development substitutes.
*
* 4. GLOBAL VECTOR CONSTRUCTION
*    PROVEN/HISTORICAL
*
*    R12 is G.  G!N is addressed at byte displacement 4*N.
*
*    BLIB recognizes the uninitialized-global value:
*
*       X'C7D3F000' + 4*N
*
*    G!0 contains the allocated global-vector extent.
*
*    Compiled-module trailers contain exported-global pairs.  BCPLMAIN
*    must merge those definitions into G before invoking START.
*
*    A general loader must perform the same operation for LOAD modules.
*
* 5. STACK / WORKSPACE INITIALIZATION
*    PROVEN/HISTORICAL
*
*    R5 is the current workspace pointer and R15 the next workspace
*    pointer.  Generated calls and entries implement this convention.
*
*    LIBHDR publishes:
*
*       G54 STACKBASE
*       G55 STACKEND
*       G56 STACKHWM
*
*    BLIB knows the historical stack fill patterns:
*
*       X'5C40E2E3'  EVENSTACK
*       X'C3D2405C'  ODDSTACK
*
*    Final startup should initialize whatever marker pattern STACKHWM
*    requires and enforce the stack-clearance policy selected by INUM.
*
* 6. BASE AND PERMANENT REGISTER INITIALIZATION
*    PROVEN
*
*    Generated code assigns:
*
*       R0   permanent zero
*       R1   4096
*       R2   8192
*       R3   12288
*       R11  system-vector base
*       R12  global-vector base
*
*    Job 943 showed why R0 matters: leaving it nonzero defeated a
*    generated comparison against zero and caused runaway recursion.
*
* 7. SYSTEM-VECTOR SERVICES
*    PROVEN/INFERRED
*
*    CGHDR defines executable service offsets:
*
*       +0   procedure return path, reached by BCR 15,11
*       +20  call-count service
*       +40  FINISH
*       +60  stack check
*       +80  stack check plus call count
*
*    The bodies below are proposals or stubs except where noted.
*    Their final semantics must match CG370, not merely factorial.
*
* 8. START INVOCATION AND NORMAL TERMINATION
*    PROVEN/INFERRED
*
*    START is global 1.  Once the runtime environment is complete,
*    BCPLMAIN transfers control to G!1.
*
*    FINISH branches through the system vector at R11+40.
*
*    LIBHDR also exposes G30 STOP.  The relationship among STOP,
*    FINISH, MVS completion codes, cleanup, and return to the caller
*    remains to be reconstructed explicitly.
*
* 9. ABNORMAL TERMINATION AND PROGRAM-INTERRUPT RECOVERY
*    HISTORICAL
*
*    This is a first-class BCPLMAIN responsibility, not an optional
*    diagnostic add-on.
*
*    BCPLMAC contains explicit STAE/SPIE state and support:
*
*       DFLG / USADFLG hold STAE/SPIE options
*       STAESW records an outstanding STAE exit
*       SPIE is identified as SVC 14
*       an STAE execute list is reserved
*       STARETRY reconstructs a saved runtime environment
*       USATCBCC records the task completion-code field
*
*    BLIB supplies high-level:
*
*       ABORT(CODE, ADDR, OLDSTACK, DATA)
*
*    and handles System/360-370 interrupt codes X'C0' through X'CF',
*    user ABENDs, fatal I/O, stack overflow, computation exhaustion,
*    BACKTRACE, USERPOSTMORTEM, and MAPSTORE.
*
*    Therefore final BCPLMAIN must provide the low-level bridge from
*    MVS recovery/program-interrupt state into BLIB's ABORT contract.
*
*    UNKNOWN:
*    The mapping from STAE/SPIE control blocks and saved registers
*    to CODE, ADDR, OLDSTACK, and DATA is not yet reconstructed.
*
*    REQUIRED FUTURE STUB:
*       establish recovery environment
*       capture completion/program-interrupt state
*       restore or identify the BCPL stack
*       invoke G!3 ABORT with the historical four arguments
*       perform final MVS cleanup if ABORT cannot continue
*
* 10. MACHINE-DEPENDENT BYTE OPERATIONS
*     HISTORICAL
*
*    BLIB explicitly states that GETBYTE and PUTBYTE are machine-code
*    routines forming part of BCPLMAIN.  Their contracts are known and
*    provisional implementations are present below.
*
* 11. STREAM, RECORD, DATASET, AND TERMINAL I/O
*     HISTORICAL / INTERFACES PARTLY UNKNOWN
*
*    LIBHDR exposes the native-facing stream surface through G11..G51,
*    including selection, character I/O, record I/O, rewind, member
*    access, parameter input, logging, and terminal discovery.
*
*    BCPLMAC contains substantial DCB, QSAM, BSAM, BPAM, TSO,
*    TPUT/TGET, and device-state definitions.  This confirms that the
*    machine-code library owned real MVS I/O control structures.
*
*    Regression 03 now provides a narrow G14 WRCH path to SYSPRINT.
*    The full selected-stream interface remains unreconstructed.
*    Add other stubs only as their contracts are recovered.
*
* 12. GETVEC / FREEVEC AND STORAGE CLEANUP
*     HISTORICAL / WIP
*
*    LIBHDR assigns G87 GETVEC and G88 FREEVEC.
*    BCPLMAC contains a vector-list head specifically for allocations
*    made by these routines and retains final storage for exit cleanup.
*    BCPLMAC VECAREA describes VECBASE, VECLEN, and VECNEXT.
*
*    Regression 27 adds the first WIP GETVEC success path.  GETVEC(N)
*    obtains N+1 payload words, matching BCPL VEC N.  The WIP block
*    carries a three-word control record before the returned payload:
*
*       +0  VECBASE   BCPL word pointer returned to the caller
*       +4  VECLEN    total bytes obtained from MVS
*       +8  VECNEXT   byte pointer to next allocation record
*       +12 payload   N+1 BCPL words
*
*    VECLIST heads those records.  This is shaped deliberately so that
*    FREEVEC and exit cleanup can be added without replacing GETVEC.
*
*    CURRENT LIMITATION:
*    the first WIP uses unconditional GETMAIN R.  Exhaustion therefore
*    ABENDs rather than returning a reconstructed historical failure
*    result.  Failure semantics, subpool policy, FREEVEC, and RESULT2
*    interaction remain to be established by later regressions.
*
* 13. DYNAMIC LOAD / UNLOAD
*     HISTORICAL
*
*    LIBHDR exposes:
*
*       G7  UNLOADALL
*       G8  LOADFORT
*       G9  UNLOAD
*       G10 LOAD
*
*    BLIB's MAPSTORE walks a load list headed through SAVEAREA!29 and
*    recognizes BCPL modules through a high-bit flag in load-list
*    word 9.
*
*    Loaded BCPL sections must have their exported globals merged
*    into G.
*
*    UNKNOWN:
*    loader-node layout and LOAD/UNLOAD arguments/results are not yet
*    complete enough for an implementation.
*
* 14. THE MACHINE-CODE LIBRARY WAS MULTI-MEMBER
*     HISTORICAL
*
*    Surviving MAKELIB JCL says BCPLIB.OBJ(BCPLMAIN) was carved up by
*    the linkage editor to produce:
*
*       $BLOCK$
*       $LOAD$
*       $TPUT$
*       BCPLMAIN
*
*    The library also contained $IOS$, BLIB, and PM as other members.
*
*    This means the final reconstruction should not assume all native
*    services necessarily remain inside one load-module entry point.
*
*    UNKNOWN CONTRACT: $LOAD$
*       Known to be carved from the BCPLMAIN object and included beside
*       BCPLMAIN in the compiler root.  It is clearly related to
*       native loading, but its exact public entry contract is pending.
*
*    UNKNOWN CONTRACT: $BLOCK$
*       Carved from the same object.  Its exact relationship
*       to block-file globals G93..G98 remains to be established.
*
*    UNKNOWN CONTRACT: $TPUT$
*       Known to be carved from the same object.  BCPLMAC defines
*       TPUT/TGET service coding, but its callable interface is
*       still unknown.
*
* 15. PLATFORM EDITING / INSTALLATION VARIANTS
*     HISTORICAL
*
*    EDITMAIN preprocesses the machine-code-library source for:
*
*       OS System/360
*       OS System/370
*       STANDARD, with no OS control-block reference
*       CMS, with no OS control-block reference
*
*    The final MVS 3.8 reconstruction should preserve the distinction
*    between architectural S/370 code and MVS-control-block coupling.
*    Host-specific choices should be documented rather than hidden.
*
* 16. POSTMORTEM AND RUNTIME STATE PUBLISHED TO BLIB
*     HISTORICAL
*
*    BLIB is interdependent with BCPLMAIN.  It expects useful
*    values for SAVEAREA, LOADPOINT, ENDPOINT, STACKBASE, STACKEND,
*    loader state, and program/data extent tests.
*
*    A runtime that merely reaches START but leaves these globals bogus
*    is a bootstrap runtime, not a complete BCPLMAIN reconstruction.
*
* OTHER RUNTIME FACILITIES KNOWN TO EXIST BUT NOT YET RECONSTRUCTED
* -----------------------------------------------------------------
* SYS3 LIBHDR identifies this runtime surface.  Its existence
* is known; this file does not pretend their full interfaces are known
* merely from the global names.
*
*   G2  SETPM
*   G3  ABORT              BLIB supplies high-level reporting; low
*                          program-interrupt capture is still unknown.
*   G4  BACKTRACE
*   G5  ERRORMESSAGE
*   G6  SAVEAREA           this WIP publishes R13>>2 provisionally.
*   G7  UNLOADALL
*   G8  LOADFORT
*   G9  UNLOAD
*   G10 LOAD               segment/module loader contract still
*                          required.
*
*   G11..G26               stream selection and record I/O, including
*                          RDCH, WRCH, READREC, WRITEREC, SKIPREC.
*
*   G27..G39               time/date, STOP, long jump, logging,
*                          and parameter services.
*
*   G40 APTOVEC            allocation primitive.
*   G41..G51               dataset/library/member discovery and close.
*
*   G52 LOADPOINT          published provisionally for main module.
*   G53 ENDPOINT            published provisionally for main module.
*   G54 STACKBASE          published by this WIP.
*   G55 STACKEND           published by this WIP.
*   G56 STACKHWM           BLIB implementation exists; not installed
*                          here.
*   G57 OS/CMS marker      known to exist; exact value convention
*                          pending.
*
*   G58..G84               library helpers, postmortem, FORTRAN bridge,
*                          break/error support.
*
*   G85 GETBYTE            implemented here.
*   G86 PUTBYTE            implemented here.
*   G87..G99               vector allocation, arithmetic, block-file
*                          MOVEBYTES services.
*
* LOAD/UNLOAD deserves its own reconstruction from historical loader
* data.  BLIB shows SAVEAREA!29 as load-list head and tests bit
* X'80000000' in load-list word 9 for BCPL modules.  That is evidence,
* not yet enough
* to implement the loader contract safely.
*
* ---------------------------------------------------------------------
*
BCPLMAIN CSECT
*
* Preserve the compiled-module base before R3 is repurposed as R.K12.
*
         LR    3,15
         BALR  10,0
         USING *,10
         ST    3,MODBASE
*
* Establish a private MVS save area before any service call.
* The generated module prefix already saved the caller's R14..R12.
*
         LA    1,MSVSAVE
         ST    13,4(1)
         ST    1,8(13)
         LR    13,1
*
* Locate L998 = module base + unsigned positive halfword at module+10.
* CG370 limits a generated section to less than 16K bytes, so LH is
* safe.
*
         LH    0,10(3)
         LR    2,3
         AR    2,0
         ST    2,MODEND
*
* Initialize a static global vector with the historical unset sentinel.
*
         LA    12,GLOBV
         LA    1,GLOBCNT
         ST    1,0(12)
         LA    2,4(12)
         L     3,=X'C7D3F004'
GINIT    ST    3,0(2)
         A     3,=F'4'
         LA    2,4(2)
         BCT   1,GINIT
*
* Find the trailer sentinel by scanning backward in two-word units.
* A pair whose second word is zero is treated as [4*MAXGN,0].
*
         L     8,MODEND
GSCAN    AH    8,=H'-8'
         L     9,4(8)
         LTR   9,9
         BC    7,GSCAN
*
* Reject modules requiring more globals than this static WIP provides.
*
         L     0,0(8)
         C     0,=F'800'
         BC    2,GTOOBIG
         ST    8,TRAILER
*
* Re-scan from the module end and install each exported global.
*
         L     8,MODEND
GINST    AH    8,=H'-8'
         L     9,4(8)
         LTR   9,9
         BC    8,GIDONE
         L     1,0(8)
         C     1,=F'800'
         BC    2,GTOOBIG
         LR    2,12
         AR    2,1
         ST    9,0(2)
         BC    15,GINST
*
* G!1 must now contain START rather than the unset sentinel.
*
GIDONE   L     4,4(12)
         C     4,=X'C7D3F004'
         BC    8,NOSTART
*
* Publish the subset of runtime globals whose representation is
* supported strongly enough for this WIP.
*
* G!6 = provisional BCPL word pointer for the current MVS save area.
*
         LR    1,13
         SRL   1,2
         ST    1,24(12)
*
* G!52/G!53 = provisional main-program word-address extent.
*
         L     1,MODBASE
         SRL   1,2
         ST    1,208(12)
         L     1,MODEND
         SRL   1,2
         ST    1,212(12)
*
* G!54/G!55 = BCPL word pointers delimiting static WIP stack/workspace.
*
         LA    1,WORK
         SRL   1,2
         ST    1,216(12)
         L     1,=A(WORKEND)
         SRL   1,2
         ST    1,220(12)
*
* G!14 = first narrow native WRCH implementation for Regression 03.
* G!76 = temporary no-op WRITEF for the factorial milestone.
* G!85/G!86 = machine-dependent byte primitives required by BLIB.
* G!87 = first WIP GETVEC dynamic-storage service.
* G!150 = provisional DEBUGINT bootstrap diagnostic service.
*
         LA    1,WRCH
         ST    1,56(12)
         LA    1,WRITEST
         ST    1,304(12)
         LA    1,GETBYTE
         ST    1,340(12)
         LA    1,PUTBYTE
         ST    1,344(12)
         LA    1,GETVEC
         ST    1,348(12)
         LA    1,DEBUGINT
         ST    1,600(12)
*
* Regression 03 output is deliberately narrow: one buffered SYSPRINT
* record.  This borrows the proven QSAM shape used by ICINT V19.
*
         XC    OUTPOS(4),OUTPOS
         MVI   OUTBUF,C' '
         MVC   OUTBUF+1(131),OUTBUF
         OPEN  (BCPOUT,(OUTPUT))
*
* Establish S, initial P/W, and the absolute-base constants required by
* generated USING 4096,1,2,3 code.
*
         LA    11,SYSV
         LA    15,WORK
         LR    5,15
         L     1,=F'4096'
         L     2,=F'8192'
         L     3,=F'12288'
*
* START receives no arguments.  Clear argument registers and linkage.
* R10 has served as our assembler base and must cease being one now.
*
         SR    6,6
         SR    7,7
         SR    8,8
         SR    9,9
         SR    10,10
*
* Job 943 makes this initialization a required runtime invariant.
*
         SR    0,0
         BCR   15,4
*
* START is expected to terminate through S.FIN.  Returning here is
* treated as a WIP runtime failure.
*
BADRETN  L     13,4(13)
         LM    14,12,12(13)
         LA    15,36
         BR    14
*
* Bootstrap failures before START.
*
GTOOBIG  L     13,4(13)
         LM    14,12,12(13)
         LA    15,16
         BR    14
NOSTART  L     13,4(13)
         LM    14,12,12(13)
         LA    15,20
         BR    14
*
* Put literals used by startup inside the startup base-register region.
*
         LTORG
*
* From here on R10 is not a runtime base.  Executable system-vector
* services use R11, whose value is SYSV in generated BCPL code.
*
         DROP  10
*
***********************************************************************
* SYSTEM VECTOR
*
* Each public offset is a four-byte branch followed by padding to the
* next 20-byte slot.  This layout is a reconstruction proposal matching
* the offsets in CGHDR; the historical instruction sequence is unknown.
***********************************************************************
SYSV     EQU   *
         USING SYSV,11
         BC    15,RETIMPL
         DS    8H
*
* S.COUNT = 20
*
SYSCOUNT BC    15,CNTIMPL
         DS    8H
*
* S.FIN = 40
*
SYSFIN   BC    15,FINIMPL
         DS    8H
*
* S.STKCK = 60
*
SYSSTK   BC    15,STKIMPL
         DS    8H
*
* S.STKCKCOUNT = 80
*
SYSSTKC  BC    15,STKCIMP
*
***********************************************************************
* PROCEDURE RETURN
*
* PROVEN for ordinary generated BCPL procedure linkage by successful
* native call/return regressions through Test 14.
***********************************************************************
RETIMPL  LM    4,6,0(5)
         BCR   15,6
*
***********************************************************************
* CALL-COUNT SERVICE -- STUB
*
* CG370 emits BAL R14,S.COUNT(R11) followed by an inline fullword.
* A minimally non-destructive stub must skip that word on return.
* Actual counter semantics remain to be reconstructed.
***********************************************************************
CNTIMPL  LA    14,4(14)
         BR    14
*
***********************************************************************
* FINISH
*
* Restore the MVS registers saved by the generated module prefix.
* This is sufficient for the current factorial milestone.  STOP/ABORT
* and propagation of a BCPL result code remain separate reconstruction
* work.
***********************************************************************
FINIMPL  L     1,OUTPOS
         LTR   1,1
         BZ    FINRETN
         PUT   BCPOUT,OUTBUF
FINRETN  L     13,4(13)
         LM    14,12,12(13)
         SR    15,15
         BR    14
*
***********************************************************************
* STACK CHECK -- STUB
*
* This currently performs no check.  Historical overflow rules, marker
* initialization, and ABORT integration must be reconstructed.
***********************************************************************
STKIMPL  BR    14
*
***********************************************************************
* STACK CHECK + CALL COUNT -- STUB
*
* CG370 places an inline fullword after this BAL form, so skip it.
***********************************************************************
STKCIMP  LA    14,4(14)
         BR    14
*
***********************************************************************
* WRCH -- FIRST NATIVE CHARACTER OUTPUT
*
* G14 WRCH receives the target EBCDIC character in R7.  For the first
* output milestone it appends bytes to one 132-byte SYSPRINT record.
* FINISH writes the buffered record.  Explicit CLOSE is deferred.
* Job 956 showed the first WIP CLOSE path looping until S322.
* Newline and general stream semantics remain future work.
*
* No MVS macro I/O occurs inside WRCH.
*
* Job 960 established an additional machine-routine return contract:
* generated code may branch relative to R4 immediately after a call.
* Procedure entry saved the caller B value at 0(R5).
* Native primitives restore R4 from that slot before returning via R6.
* R0 and R1-R3 are permanent generated-code registers.
* Native primitives preserve them.
***********************************************************************
WRCH     L     14,OUTPOS
         LA    4,132
         CR    14,4
         BNL   WRCHRTN
         LA    4,OUTBUF
         AR    4,14
         STC   7,0(4)
         LA    14,1(14)
         ST    14,OUTPOS
WRCHRTN  L     4,0(5)
         BCR   15,6
*
***********************************************************************
* TEMPORARY WRITEF
*
* Factorial-only accommodation.  Tests 11-14 prove argument 1 in R7,
* argument 2 in R8, and argument 3 in R9 for ordinary BCPL calls.
* Do not modify R0 or R1-R3.
***********************************************************************
WRITEST  L     4,0(5)
         BCR   15,6
*
***********************************************************************
* GETBYTE(S,I) -> R7
*
* S is a BCPL word pointer.  I is an unrestricted byte offset.
***********************************************************************
GETBYTE  LR    14,7
         SLL   14,2
         AR    14,8
         SR    7,7
         IC    7,0(14)
         L     4,0(5)
         BCR   15,6
*
***********************************************************************
* PUTBYTE(S,I,BYTE)
*
* S in R7, I in R8, BYTE in R9.  Store the low eight bits.
***********************************************************************
PUTBYTE  LR    14,7
         SLL   14,2
         AR    14,8
         STC   9,0(14)
         L     4,0(5)
         BCR   15,6
*
***********************************************************************
* GETVEC(N) -> R7 -- WIP DYNAMIC STORAGE
*
* Regression 27 success-path implementation.
*
* BCPL VEC N has indices 0..N, so GETVEC(N) supplies N+1 payload
* fullwords.  Twelve private bytes precede the payload and mirror the
* historical VECAREA fields VECBASE, VECLEN, and VECNEXT.
*
* GETMAIN R is intentionally unconditional for this first rung.
* Allocation failure semantics are deferred to the later edge test.
*
* GETMAIN uses R0/R1.  Generated BCPL requires R0=0 and R1-R3 to hold
* permanent constants, so save and restore R0-R3 around the MVS call.
***********************************************************************
GETVEC   STM   0,3,GVRSAVE
         LR    10,7
         LA    10,1(10)
         SLL   10,2
         LA    10,12(10)
         ST    10,GVRLEN
         GETMAIN R,LV=(10)
*
* R1 is the byte address returned by GETMAIN.  Build the WIP VECAREA
* record in the allocated block and chain it at VECLIST.
*
         LR    14,1
         LA    7,12(14)
         SRL   7,2
         ST    7,0(14)
         L     10,GVRLEN
         ST    10,4(14)
         L     10,VECLIST
         ST    10,8(14)
         ST    14,VECLIST
*
* Restore permanent generated-code registers and the caller's B.
* R7 deliberately retains the BCPL word pointer result.
*
         LM    0,3,GVRSAVE
         L     4,0(5)
         BCR   15,6
*
***********************************************************************
* DEBUGINT -- PROVISIONAL BOOTSTRAP DIAGNOSTIC
*
* G150 DEBUGINT receives a signed 32-bit integer in R7.
* It appends decimal text to the same SYSPRINT record used by WRCH.
* This is not a recovered historical BCPL library interface.
* It must not be confused with WRITEN or WRITEF.
*
* CVD creates packed decimal and UNPK creates zoned digits.
* The final zone is normalized after the sign nibble is consumed.
* Leading zeroes are suppressed.  Zero itself emits one digit.
***********************************************************************
DEBUGINT LTR   7,7
         BNM   DBGCVT
         LA    10,C'-'
         BAL   14,DBGAPND
DBGCVT   CVD   7,DECPACK
         UNPK  DECZON(15),DECPACK(8)
         OI    DECZON+14,X'F0'
         LA    8,DECZON
         LA    9,15
DBGSKIP  CLI   0(8),C'0'
         BNE   DBGOUT
         LA    4,1
         CR    9,4
         BE    DBGOUT
         LA    8,1(8)
         BCT   9,DBGSKIP
DBGOUT   SR    10,10
         IC    10,0(8)
         BAL   14,DBGAPND
         LA    8,1(8)
         BCT   9,DBGOUT
         L     4,0(5)
         BCR   15,6
*
* Append one EBCDIC byte from R10.  R14 is local linkage.
*
DBGAPND  L     4,OUTPOS
         LA    7,132
         CR    4,7
         BNL   DBGARET
         LA    7,OUTBUF
         AR    7,4
         STC   10,0(7)
         LA    4,1(4)
         ST    4,OUTPOS
DBGARET  BR    14
*
***********************************************************************
* WIP DATA
***********************************************************************
         DS    0F
MODBASE  DC    F'0'
MODEND   DC    F'0'
TRAILER  DC    F'0'
*
* GETVEC WIP allocation state.
* VECLIST is a byte pointer to the first three-word control record.
*
VECLIST  DC    F'0'
GVRLEN   DC    F'0'
GVRSAVE  DS    4F
*
* Private MVS save area used while BCPLMAIN owns R13.
*
MSVSAVE  DS    18F
*
* Static bootstrap global-vector capacity.
* SYS3 FIRSTFREEGLOBAL is 150.
* User globals therefore begin beyond that boundary.
* Reserve modest room while dynamic G allocation is unreconstructed.
*
GLOBCNT  EQU   200
GLOBV    DC    F'200'
         DS    200F
*
* Regression 03 output state.  SYSPRINT is supplied by the GO step.
* Historical stream/DCB support was richer; this is only the first
* observable character-output rung.  Normal step termination currently
* owns DCB cleanup; explicit CLOSE remains under reconstruction.
*
DECPACK  DS    D
DECZON   DS    CL15
OUTPOS   DC    F'0'
OUTBUF   DS    CL132
BCPOUT   DCB   DDNAME=SYSPRINT,DSORG=PS,MACRF=PM
*
* Static development workspace.  This is not the historical allocation
* policy.  Replace with recovered MVS storage management and stack
* marker initialization when that contract is understood.
*
WORK     DS    4096F
WORKEND  EQU   *
*
         END   BCPLMAIN
