#!/usr/bin/env python3
"""Delete the explicit dspal-managed BCPL dataset set."""

from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CORE_PATH = ROOT / "tools" / "dspal-core.py"


def load_core():
    spec = importlib.util.spec_from_file_location("dspal_core", CORE_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {CORE_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


core = load_core()
DspalError = core.DspalError


def managed_dsns(config: dict[str, Any]) -> list[tuple[str, str]]:
    return [
        (logical, core.full_dsn(config, spec))
        for logical, spec in config["datasets"].items()
    ]


def purge_deck(
    config: dict[str, Any],
    selected: list[tuple[str, str]],
    *,
    redact_password: bool,
) -> str:
    lines = core.authenticated_job_card(
        config, "DSPALPUR", "DSPAL PURGEBCPL", redact_password=redact_password
    )
    lines.extend(
        [
            "//* GENERATED BY DSPAL FROM CONFIG/DSPAL.YAML",
            "//* DELETE ONLY THE EXPLICIT MANAGED DATASET SET",
            "//DELETE   EXEC PGM=IKJEFT01",
            "//SYSTSPRT DD  SYSOUT=*",
            "//SYSTSIN  DD  *",
        ]
    )
    if selected:
        for logical, dsn in selected:
            lines.append(f" /* {logical}")
            lines.append(f" DELETE '{dsn}'")
    else:
        lines.append(" /* NO EXISTING MANAGED DATASETS SELECTED")
    lines.append("/*")
    return "\n".join(lines) + "\n"


def confirm_deletion(selected: list[tuple[str, str]]) -> None:
    print("purgebcpl will delete these managed datasets:")
    for logical, dsn in selected:
        print(f"  {logical:<9} {dsn}")
    print()
    try:
        answer = input("Type YES to delete them: ")
    except EOFError as exc:
        raise DspalError("confirmation required; rerun interactively or use --yes") from exc
    if answer.strip() != "YES":
        raise DspalError("purgebcpl cancelled; confirmation was not YES")


def cmd_purgebcpl(config: dict[str, Any], yes: bool, show_jcl: bool) -> int:
    all_managed = managed_dsns(config)

    if show_jcl:
        sys.stdout.write(purge_deck(config, all_managed, redact_password=True))
        return 0

    core.require_reader_ready(config)
    preflight_job, _, inventory = core.managed_inventory(config)
    selected = [
        (logical, dsn)
        for logical, dsn in all_managed
        if inventory[logical] is not None
    ]

    if not selected:
        print(f"purgebcpl preflight completed as JOB {preflight_job}")
        print("No managed datasets exist; nothing to delete.")
        return 0

    if not yes:
        confirm_deletion(selected)

    job, _ = core.submit_and_wait(
        config,
        purge_deck(config, selected, redact_password=False),
        max_rc=0,
    )
    print(f"purgebcpl preflight completed as JOB {preflight_job}")
    print(f"purgebcpl deletion completed as JOB {job}")
    for logical, dsn in selected:
        print(f"  {logical:<9} deleted {dsn}")
    return 0


def make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="dspal purgebcpl",
        description=(
            "Delete only the datasets explicitly managed by config/dspal.yaml. "
            "Confirmation is required unless --yes is specified."
        ),
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--yes",
        action="store_true",
        help="delete the existing managed dataset set without interactive confirmation",
    )
    mode.add_argument(
        "--show-jcl",
        action="store_true",
        help="emit worst-case delete JCL without submitting it; password is redacted",
    )
    return parser


def main() -> int:
    try:
        args = make_parser().parse_args()
        config = core.load_config()
        return cmd_purgebcpl(config, args.yes, args.show_jcl)
    except (DspalError, OSError, ValueError) as exc:
        print(f"dspal: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
