//HELLOWOR JOB (MVS),'ASM LINK GO',CLASS=A,MSGCLASS=A,
//             MSGLEVEL=(1,1)
//* GENERATED FROM HELLO-WORLD.ASM; LISTING=LIGHT
//* THE ASM SOURCE IS INLINED BELOW. REGENERATE AFTER EDITING IT.
//ASM      EXEC PGM=IFOX00,
//             PARM='OBJECT,NODECK,NOLIST,NOXREF',REGION=256K
//SYSLIB   DD  DSN=SYS1.MACLIB,DISP=SHR
//SYSUT1   DD  UNIT=SYSDA,SPACE=(1700,(600,100))
//SYSUT2   DD  UNIT=SYSDA,SPACE=(1700,(300,50))
//SYSUT3   DD  UNIT=SYSDA,SPACE=(1700,(300,50))
//SYSPRINT DD  SYSOUT=*
//SYSPUNCH DD  DUMMY
//SYSGO    DD  DSN=&&OBJSET,UNIT=SYSDA,SPACE=(80,(300,100)),
//             DISP=(MOD,PASS)
//SYSIN    DD  *
HELLO    CSECT
HELLO    AMODE 24
HELLO    RMODE 24
         STM   14,12,12(13)       SAVE CALLER REGISTERS
         BALR  12,0
         USING *,12

         OPEN  (PRINT,(OUTPUT))

         PUT   PRINT,MESSAGE

         CLOSE (PRINT)

         LM    14,12,12(13)       RESTORE CALLER REGISTERS
         SR    15,15              RETURN CODE = 0
         BR    14

MESSAGE  DC    CL80'HELLO, WORLD!'

PRINT    DCB   DDNAME=SYSPRINT,                                   X
               DSORG=PS,                                         X
               MACRF=PM,                                         X
               RECFM=F,                                          X
               LRECL=80

         END   HELLO
/*
//*
//LKED     EXEC PGM=IEWL,PARM='LET,NCAL',REGION=256K,
//             COND=(4,LT,ASM)
//SYSLIN   DD  DSN=&&OBJSET,DISP=(OLD,DELETE)
//         DD  *
  ENTRY HELLO
  NAME RUNMOD(R)
/*
//SYSLMOD  DD  DSN=&&GOSET(RUNMOD),UNIT=SYSDA,
//             SPACE=(1024,(50,20,1)),DISP=(MOD,PASS)
//SYSUT1   DD  UNIT=SYSDA,SPACE=(1024,(50,20))
//SYSPRINT DD  SYSOUT=*
//*
//GO       EXEC PGM=*.LKED.SYSLMOD,
//             COND=((4,LT,ASM),(4,LT,LKED))
//SYSPRINT DD  SYSOUT=*,DCB=(RECFM=FB,LRECL=132,BLKSIZE=132)
//SYSUDUMP DD  SYSOUT=*
//
